/**
  *             Copyright (C) SOJO Electric CO., Ltd. 2017-2018. All right reserved.
  * @file:      point_table_config.c
  * @brief:     The point_table_config  of the project.
  * @version:   ver 1.1
  * @author:    Mr.Sun
  * @date:      2018-05-09
  * @update:    [2018-05-09][name][change]
  */
	
	
/* INCLUDES FILES ------------------------------------------------------------*/
#include "common_data.h"
#include "point_table_config.h"

/* 遥信 */
struct tagTelesignalCfg TelesignalCfg[] = 
{
    { 1,  "开关分位",            &g_Telesignal[ADDR_OPEN]},
    { 1,  "开关合位",            &g_Telesignal[ADDR_CLOSE]},
    { 1,  "储能有压",            &g_Telesignal[ADDR_CAP_UNDER_VOLTAGE]},
    { 1,  "低气压",              &g_Telesignal[ADDR_LOW_PRESSURE]},
    { 1,  "电源故障告警",        &g_Telesignal[ADDR_POWERFAULTALARM]},
    { 1,  "电池欠压告警",        &g_Telesignal[ADDR_BATTERY_UNDERVOLTAGE_ALARM]},
    { 1,  "电池活化状态",        &g_Telesignal[ADDR_BATTERYACTIVATIONSTATUS]},
    { 1,  "电池失电告警",        &g_Telesignal[ADDR_BATTERY_LOSS_ALARM]},
    { 1,  "工作模式",            &g_Telesignal[ADDR_BREAK_CONTACT]},
    { 1,  "重合压板",            &g_Telesignal[ADDR_RECLOSEHARDSTRAP]},
    { 1,  "保护压板",            &g_Telesignal[ADDR_FUNCTION_HARDSTRAP]},
    { 1,  "远方/就地",           &g_Telesignal[ADDR_REMOTE_EARTH]},
    { 1,  "短路故障",            &g_Telesignal[ADDR_SHORT_CIRCUIT_FAULT]},
    { 1,  "零序故障",            &g_Telesignal[ADDR_EARTHING_FAULT]},
    { 1,  "保护动作",            &g_Telesignal[ADDR_PROTECTION_ACT]},
    { 1,  "保护闭锁",            &g_Telesignal[ADDR_PROTECTION_CLOCK]},
    { 1,  "合闸闭锁",            &g_Telesignal[ADDR_CLOSING_CLOCK]},	
    { 1,  "分闸闭锁",            &g_Telesignal[ADDR_OPENING_CLOCK]},
    { 1,  "重合动作",            &g_Telesignal[ADDR_RECLOSE_ACT]},
    { 1,  "重合闭锁",            &g_Telesignal[ADDR_RECLOSE_CLOCK]},
    { 1,  "装置故障",            &g_Telesignal[ADDR_DEVICE_FAULT]},
    { 1,  "自检异常",            &g_Telesignal[ADDR_SELF_CHECK_ABNOMAL]},
    { 1,  "通讯",                &g_Telesignal[ADDR_COMMUNICATION]},
    { 1,  "开关类型",            &g_Telesignal[ADDR_SWTICHCLASS]},	
    { 1,  "电池故障告警",        &g_Telesignal[ADDR_BATTERY_FAULT_ALARM]},
    { 1,  "双点开关分合",        &g_Telesignal[ADDR_DOUBLE_SWITCH]},
    { 1,  "控制回路断线",        &g_Telesignal[ADDR_CONTROL_LOOP_DISCONNECTION]},
    { 1,  "A相过流一段",         &g_Telesignal[ADDR_OVERCURRENT_IA_1]},
    { 1,  "B相过流一段",         &g_Telesignal[ADDR_OVERCURRENT_IB_1]},	
    { 1,  "C相过流一段",         &g_Telesignal[ADDR_OVERCURRENT_IC_1]},
    { 1,  "A相过流二段",         &g_Telesignal[ADDR_OVERCURRENT_IA_2]},
    { 1,  "B相过流二段",         &g_Telesignal[ADDR_OVERCURRENT_IB_2]},	
    { 1,  "C相过流二段",         &g_Telesignal[ADDR_OVERCURRENT_IC_2]},
    { 1,  "A相过流三段",         &g_Telesignal[ADDR_OVERCURRENT_IA_3]},
    { 1,  "B相过流三段",         &g_Telesignal[ADDR_OVERCURRENT_IB_3]},	
    { 1,  "C相过流三段",         &g_Telesignal[ADDR_OVERCURRENT_IC_3]},
    { 1,  "零序过流一段",        &g_Telesignal[ADDR_OVERCURRENT_I0_1]},
    { 1,  "零序过流二段",        &g_Telesignal[ADDR_OVERCURRENT_I0_2]},		
    { 1,  "A相后加速",           &g_Telesignal[ADDR_OVERCURRENT_ACC_IA]},
    { 1,  "B相后加速",           &g_Telesignal[ADDR_OVERCURRENT_ACC_IB]},
    { 1,  "C相后加速",           &g_Telesignal[ADDR_OVERCURRENT_ACC_IC]},
    { 1,  "A相反时限",           &g_Telesignal[ADDR_OVERCURRENT_INVERSE_IA]},
    { 1,  "B相反时限",           &g_Telesignal[ADDR_OVERCURRENT_INVERSE_IB]},
    { 1,  "C相反时限",           &g_Telesignal[ADDR_OVERCURRENT_INVERSE_IC]},	
    { 1,  "一次重合闸",          &g_Telesignal[ADDR_RECLOSE_PROTECTION_1]},
    { 1,  "二次重合闸",          &g_Telesignal[ADDR_RECLOSE_PROTECTION_2]},
    { 1,  "三次重合闸",          &g_Telesignal[ADDR_RECLOSE_PROTECTION_3]},
    { 1,  "四次重合闸",          &g_Telesignal[ADDR_RECLOSE_PROTECTION_4]},
    { 1,  "重合闭锁",            &g_Telesignal[ADDR_RECLOSE_CLOCK_PROTECTION]},	
    { 1,  "零序一次重合",        &g_Telesignal[ADDR_ZERO_RECLOSE_PROTECTION_1]},
    { 1,  "零序二次重合",        &g_Telesignal[ADDR_ZERO_RECLOSE_PROTECTION_2]},			
    { 1,  "闭锁二次重合",        &g_Telesignal[ADDR_CLOCK_SECONDARY_CLOSE]},
    { 1,  "失电分闸",            &g_Telesignal[ADDR_LOSS_TRIP]},
    { 1,  "得电合闸",            &g_Telesignal[ADDR_GET_CLOSSING_EVENT]},
    { 1,  "合闸于故障",          &g_Telesignal[ADDR_CLOSING_FAULT]},
    { 1,  "保护闭锁",            &g_Telesignal[ADDR_PROTECT_CLOCK]},	
    { 1,  "双侧有压禁止合闸",    &g_Telesignal[ADDR_DOUBLE_PROHIBIT_CLOSSING]},
    { 1,  "单侧失压合闸",        &g_Telesignal[ADDR_SINGLE_LOSS_CLOSING_EVENT]},
    { 1,  "残压闭锁合闸",        &g_Telesignal[ADDR_REMAIN_CLOCK_CLOSSING]},	
    { 1,  "接地故障跳闸",        &g_Telesignal[ADDR_U0_EARTHING_FAULT_TRIP]},
    { 1,  "小信号选线跳闸",      &g_Telesignal[ADDR_SMALL_SIGNAL_GROUND_LINE_TRIP]},
    { 1,  "遮断电流",            &g_Telesignal[ADDR_BREAKINGCURRENT]},	
    { 1,  "过负荷",              &g_Telesignal[ADDR_OVERLOAD_EVENT]},
    { 1,  "重过载",              &g_Telesignal[ADDR_HAVEY_OVERLOAD_EVENT]},
    { 1,  "过压保护",            &g_Telesignal[ADDR_OVER_VOLTAGE_PROTECTION]},		
    { 1,  "过频保护",            &g_Telesignal[ADDR_OVER_FREQUEBNCY_PROTECTION]},
    { 1,  "低压保护",            &g_Telesignal[ADDR_DOWN_VOLTAGE_PROTECTION]},
    { 1,  "低频保护",            &g_Telesignal[ADDR_DOWN_FREQUEBNCY_PROTECTION]},
    { 1,  "Uab越上限",           &g_Telesignal[ADDR_OVER_LIMIT_Uab_UP]},
    { 1,  "Uab越下限",           &g_Telesignal[ADDR_OVER_LIMIT_Uab_DOWN]},	
    { 1,  "UBC越上限",           &g_Telesignal[ADDR_OVER_LIMIT_UBC_UP]},
    { 1,  "UBC越下限",           &g_Telesignal[ADDR_OVER_LIMIT_UBC_DOWN]},	
    { 1,  "Uca越上限",           &g_Telesignal[ADDR_OVER_LIMIT_Uca_UP]},	
    { 1,  "Uca越下限",           &g_Telesignal[ADDR_OVER_LIMIT_Uca_DOWN]},	
    { 1,  "U0越上限",            &g_Telesignal[ADDR_OVER_LIMIT_U0_UP]},	
    { 1,  "U0越下限",            &g_Telesignal[ADDR_OVER_LIMIT_U0_DOWN]},	
    { 1,  "Ia越上限",            &g_Telesignal[ADDR_OVER_LIMIT_IA_UP]},
    { 1,  "Ia越下限",            &g_Telesignal[ADDR_OVER_LIMIT_IA_DOWN]},	
    { 1,  "Ib越上限",            &g_Telesignal[ADDR_OVER_LIMIT_IB_UP]},
    { 1,  "Ib越下限",            &g_Telesignal[ADDR_OVER_LIMIT_IB_DOWN]},	
    { 1,  "Ic越上限",            &g_Telesignal[ADDR_OVER_LIMIT_IC_UP]},	
    { 1,  "Ic越下限",            &g_Telesignal[ADDR_OVER_LIMIT_IC_DOWN]},	
    { 1,  "I0越上限",            &g_Telesignal[ADDR_OVER_LIMIT_I0_UP]},	
    { 1,  "I0越下限",            &g_Telesignal[ADDR_OVER_LIMIT_I0_DOWN]},		
    { 1,  "DC_U越上限",          &g_Telesignal[ADDR_OVER_LIMIT_DC_U_UP]},	
    { 1,  "DC_U越下限",          &g_Telesignal[ADDR_OVER_LIMIT_DC_U_DOWN]},	
    { 1,  "DC_I越上限",          &g_Telesignal[ADDR_OVER_LIMIT_DC_I_UP]},	
    { 1,  "DC_I越下限",          &g_Telesignal[ADDR_OVER_LIMIT_DC_I_DOWN]},		
    { 1,  "装置掉电",            &g_Telesignal[ADDR_DEVICE_POWER_DOWN]},
};
	
/* 遥测 */
struct tagTelemetryCfg TelemetryCfg[] = 
{
//   使能      名称                    值                           单位                 校准系数                             零漂                             死区	
    { 1,    "频率(f)",          &g_Telemetry[ADDR_F],               "Hz",       &g_CalibrateFactor[CALIFACTOR_F],      &g_Parameter[ZERODRIFT_F],      &g_Parameter[DEADZONE_F]},
    { 1,    "A相电流(Ia)",      &g_Telemetry[ADDR_IA],              "A",        &g_CalibrateFactor[CALIFACTOR_Ia],     &g_Parameter[ZERODRIFT_Ia],     &g_Parameter[DEADZONE_Ia]},
    { 1,    "A相电流(Ib)",      &g_Telemetry[ADDR_IB],              "A",        &g_CalibrateFactor[CALIFACTOR_Ib],     &g_Parameter[ZERODRIFT_Ib],     &g_Parameter[DEADZONE_Ib]},
    { 1,    "A相电流(Ic)",      &g_Telemetry[ADDR_IC],              "A",        &g_CalibrateFactor[CALIFACTOR_Ic],     &g_Parameter[ZERODRIFT_Ic],     &g_Parameter[DEADZONE_Ic]},	
    { 1,    "零序电流(I0)",     &g_Telemetry[ADDR_I0],              "A",        &g_CalibrateFactor[CALIFACTOR_I0],     &g_Parameter[ZERODRIFT_I0],     &g_Parameter[DEADZONE_I0]},
    { 1,    "线电压(Uab)",      &g_Telemetry[ADDR_Uab],             "V",        &g_CalibrateFactor[CALIFACTOR_Uab],    &g_Parameter[ZERODRIFT_Uab],    &g_Parameter[DEADZONE_Uab]},
    { 1,    "线电压(Ubc)",      &g_Telemetry[ADDR_Ubc],             "V",        &g_CalibrateFactor[CALIFACTOR_Ubc],    &g_Parameter[ZERODRIFT_Ubc],    &g_Parameter[DEADZONE_Ubc]},
    { 1,    "线电压(Uca)",      &g_Telemetry[ADDR_Uac],             "V",        &g_CalibrateFactor[CALIFACTOR_Uac],    &g_Parameter[ZERODRIFT_Uac],    &g_Parameter[DEADZONE_Uac]},
    { 1,    "零序电压(U0)",     &g_Telemetry[ADDR_U0],              "V",        &g_CalibrateFactor[CALIFACTOR_U0],     &g_Parameter[ZERODRIFT_U0],     &g_Parameter[DEADZONE_U0]},
    { 1,    "线电压(UAB)",      &g_Telemetry[ADDR_UAB],             "V",        &g_CalibrateFactor[CALIFACTOR_UAB],    &g_Parameter[ZERODRIFT_UAB],    &g_Parameter[DEADZONE_UAB]},
    { 1,    "线电压(UBC)",      &g_Telemetry[ADDR_UBC],             "V",        &g_CalibrateFactor[CALIFACTOR_UBC],    &g_Parameter[ZERODRIFT_UBC],    &g_Parameter[DEADZONE_UBC]},
    { 1,    "有功功率(P)",      &g_Telemetry[ADDR_P],               "kW",       &g_CalibrateFactor[CALIFACTOR_P],      &g_Parameter[ZERODRIFT_P],      &g_Parameter[DEADZONE_P]},
    { 1,    "无功功率(Q)",      &g_Telemetry[ADDR_Q],               "kVar",     &g_CalibrateFactor[CALIFACTOR_Q],      &g_Parameter[ZERODRIFT_Q],      &g_Parameter[DEADZONE_Q]},
    { 1,    "视在功率(S)",      &g_Telemetry[ADDR_S],               "kVA",      &g_CalibrateFactor[CALIFACTOR_S],      &g_Parameter[ZERODRIFT_S],      &g_Parameter[DEADZONE_S]},
    { 1,    "功率因数(pf)",     &g_Telemetry[ADDR_PF],               "-",       &g_CalibrateFactor[CALIFACTOR_PF],     &g_Parameter[ZERODRIFT_PF],     &g_Parameter[DEADZONE_PF]},
    { 1,    "∠U0_I0",          &g_Telemetry[ADDR_AIPHY_U0_I0],      "°",       &g_CalibrateFactor[CALIFACTOR_L0],     NULL,                            NULL},
    { 1,    "∠Uab_UBC",        &g_Telemetry[ADDR_ALPHY_Uab_UBC],    "°",       &g_CalibrateFactor[CALIFACTOR_LU],     NULL,                            NULL},
    { 1,    "直流电压1",        &g_Telemetry[ADDR_DC1],              "V",       &g_CalibrateFactor[CALIFACTOR_DC1],    &g_Parameter[ZERODRIFT_DC1],    &g_Parameter[DEADZONE_DC1]},
    { 1,    "直流电压2",        &g_Telemetry[ADDR_DC2],              "V",       &g_CalibrateFactor[CALIFACTOR_DC2],    &g_Parameter[ZERODRIFT_DC2],    &g_Parameter[DEADZONE_DC2]},
    { 1,    "温度(T)",          &g_Telemetry[ADDR_T],                "°C",      &g_CalibrateFactor[CALIFACTOR_T],      &g_Parameter[ZERODRIFT_T],      &g_Parameter[DEADZONE_T]},
 
    { 1,    "一次Ia",           &g_Telemetry[ADDR_Ia_ONCE],          "A",       NULL,                                  NULL,                           NULL},
    { 1,    "一次Ib",           &g_Telemetry[ADDR_Ib_ONCE],          "A",       NULL,                                  NULL,                           NULL},
    { 1,    "一次Ic",           &g_Telemetry[ADDR_Ic_ONCE],          "A",       NULL,                                  NULL,                           NULL},
    { 1,    "一次I0",           &g_Telemetry[ADDR_I0_ONCE],          "A",       NULL,                                  NULL,                           NULL},
    { 1,    "一次Uab",          &g_Telemetry[ADDR_Uab_ONCE],         "kV",      NULL,                                  NULL,                           NULL},
    { 1,    "一次Ubc",          &g_Telemetry[ADDR_Ubc_ONCE],         "kV",      NULL,                                  NULL,                           NULL},
    { 1,    "一次Uca",          &g_Telemetry[ADDR_Uac_ONCE],         "kV",      NULL,                                  NULL,                           NULL},
    { 1,    "一次U0",           &g_Telemetry[ADDR_U0_ONCE],          "kV",      NULL,                                  NULL,                           NULL},
    { 1,    "一次UAB",          &g_Telemetry[ADDR_UAB_ONCE],         "kV",      NULL,                                  NULL,                           NULL},
    { 1,    "一次UBC",          &g_Telemetry[ADDR_UBC_ONCE],         "kV",      NULL,                                  NULL,                           NULL},
    { 1,    "一次P",            &g_Telemetry[ADDR_P_ONCE],           "kW",      NULL,                                  NULL,                           NULL},
    { 1,    "一次Q",            &g_Telemetry[ADDR_Q_ONCE],           "kvar",    NULL,                                  NULL,                           NULL},
    { 1,    "一次S",            &g_Telemetry[ADDR_S_ONCE],           "kVA",     NULL,                                  NULL,                           NULL},		
    { 0,    "电压合格率",       &g_Telemetry[VOLTAGE_PASS_RATE],     "Hz",      NULL,                                  NULL,                           NULL},

    { 1,    "三次谐波Uab",      &g_Telemetry[THIRDHARMONIC_Uab],     "V",       NULL,                                  NULL,                           NULL},	
    { 1,    "三次谐波Ubc",      &g_Telemetry[THIRDHARMONIC_Ubc],     "V",       NULL,                                  NULL,                           NULL},
    { 1,    "三次谐波Uca",      &g_Telemetry[THIRDHARMONIC_Uca],     "V",       NULL,                                  NULL,                           NULL},
    { 1,    "三次谐波U0",       &g_Telemetry[THIRDHARMONIC_U0],      "V",       NULL,                                  NULL,                           NULL},
//    { 1,    "三次谐波UAB",      &g_Telemetry[THIRDHARMONIC_UAB],    "V",      NULL,                                  NULL,                           NULL},
//    { 1,    "三次谐波UBC",      &g_Telemetry[THIRDHARMONIC_UBC],    "V",      NULL,                                  NULL,                           NULL},
    { 1,    "三次谐波Ia",       &g_Telemetry[THIRDHARMONIC_Ia],      "A",       NULL,                                  NULL,                           NULL},
    { 1,    "三次谐波Ib",       &g_Telemetry[THIRDHARMONIC_Ib],      "A",       NULL,                                  NULL,                           NULL},
    { 1,    "三次谐波Ic",       &g_Telemetry[THIRDHARMONIC_Ic],      "A",       NULL,                                  NULL,                           NULL},
    { 1,    "三次谐波I0",       &g_Telemetry[THIRDHARMONIC_I0],      "A",       NULL,                                  NULL,                           NULL},	
    { 1,    "五次谐波Uab",      &g_Telemetry[FIFTHHARMONIC_Uab],     "V",       NULL,                                  NULL,                           NULL},	
    { 1,    "五次谐波Ubc",      &g_Telemetry[FIFTHHARMONIC_Ubc],     "V",       NULL,                                  NULL,                           NULL},
    { 1,    "五次谐波Uca",      &g_Telemetry[FIFTHHARMONIC_Uca],     "V",       NULL,                                  NULL,                           NULL},
    { 1,    "五次谐波U0",       &g_Telemetry[FIFTHHARMONIC_U0],      "V",       NULL,                                  NULL,                           NULL},
//    { 1,    "五次谐波UAB",     &g_Telemetry[FIFTHHARMONIC_UAB],     "V",      NULL,                                  NULL,                           NULL},
//    { 1,    "五次谐波UBC",     &g_Telemetry[FIFTHHARMONIC_UBC],     "V",      NULL,                                  NULL,                           NULL},
    { 1,    "五次谐波Ia",        &g_Telemetry[FIFTHHARMONIC_Ia],     "A",       NULL,                                  NULL,                           NULL},
    { 1,    "五次谐波Ib",        &g_Telemetry[FIFTHHARMONIC_Ib],     "A",       NULL,                                  NULL,                           NULL},
    { 1,    "五次谐波Ic",        &g_Telemetry[FIFTHHARMONIC_Ic],     "A",       NULL,                                  NULL,                           NULL},
    { 1,    "五次谐波I0",        &g_Telemetry[FIFTHHARMONIC_I0],     "A",       NULL,                                  NULL,                           NULL},		
	
};	

/* 校准系数 */
struct tagCalibrateFactor CalibrateFactorCfg[] = 
{
//   使能          名称                  校准值	
    { 1,    "频率(f)校准系数",           50.00f},
    { 1,    "A相电流(Ia)校准系数",       5.00f},
    { 1,    "B相电流(Ib)校准系数",       5.00f},
    { 1,    "C相电流(Ic)校准系数",       5.00f},
    { 1,    "零序电流(I0)校准系数",      1.00f},
    { 1,    "线电压(Uab)校准系数",       100.00f},
    { 1,    "线电压(Ubc)校准系数",       100.00f},
    { 1,    "线电压(Uca)校准系数",       100.00f},
    { 1,    "线电压(U0)校准系数",        50.00f},
    { 1,    "线电压(UAB)校准系数",       100.00f},
    { 1,    "线电压(UBC)校准系数",       100.00f},
	
    { 0,    "有功功率校准系数(无效)",    1},
    { 0,    "无功功率校准系数(无效)",    1},
    { 0,    "视在功率校准系数(无效)",    1},
    { 0,    "功率因数校准系数(无效)",    1},
    { 0,    "零序角度校准系数(无效)",    1},
    { 0,    "电压角度校准系数(无效)",    1},

    { 1,    "直流电压1校准系数",         24},
    { 1,    "直流电压2校准系数",         24},
    { 1,    "温度校准系数",              0},
    { 1,    "UA_IA夹角校准系数",         0},
    { 1,    "UB_IB夹角校准系数",         0},
    { 1,    "UC_IC夹角校准系数",         0},
    { 1,    "U0_I0夹角校准系数",         0},
    { 1,    "UA_IB夹角校准系数",         0},		
};
	
/* 定值0区 */
struct tagValueParaCfg ParameterCfg[] = 
{
//   使能  菜单编号       名称                            值                         单位      上限        下限   数据类型     显示内容           备注
    { 1,      1,      "操作机构",        &g_Parameter[OPERATING_MECHANISM],          "-",       1,           0,     2,     {"弹簧", "永磁"    },   " "   },    
    { 1,      1,      "开关类型",        &g_Parameter[SWITCH_TYPE],                  "-",       1,           0,     2,     {"断路器", "负荷开关"},   " "   }, 
    { 1,      1,      "断路器模式",      &g_Parameter[BREAK_WORK_MODE],              "-",       4,           0,     5,     {"无","常规保护","电压时间型","电压电流型","电流计数型"},   " "   },	
    { 1,      1,      "负荷开关模式",    &g_Parameter[LOAD_WORK_MODE],               "-",       4,           0,     5,     {"无","常规保护","电压时间型","电压电流型","分界"},   " "   }, 
    { 1,      1,      "联络开关识别",    &g_Parameter[CONNECT_SWITCH_RECOGNIZE],     "-",       1,           0,     2,     {"手动", "自动"    },   " "   },	
    { 1,      1,      "永磁输出翻转",    &g_Parameter[OUTPUT_OVERTURN],              "-",       1,           0,     2,     {"不翻转", "翻转"  },   " "   }, 
    { 1,      1,      "合闸欠压定值",    &g_Parameter[CAP_UNDERVOLTAGE_CLOSING],     "V",     250.00f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      1,      "分闸欠压定值",    &g_Parameter[CAP_UNDERVOLTAGE_OPENING],     "V",     250.00f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      1,      "电容欠压系数",    &g_Parameter[CAP_UNDERVOLTAGE_FACTOR],      "-",      2.01f,      1.01f,   0,     {"-",  "-"         },   " "   },	    
    { 1,      1,      "一次变比_U",      &g_Parameter[RATIO_U_ONE_TURN],             "V",    100000.00f,   0.00f,   0,     {"-",  "-"         },   " "    }, 
    { 1,      1,      "二次变比_U",      &g_Parameter[RATIO_U_SECONDARY],            "V",     1000.00f,   0.00f,    0,     {"-",  "-"         },   " "    },	
    { 1,      1,      "一次变比_U0",     &g_Parameter[RATIO_U0_ONE_TURN],            "V",     10000.00f,   0.00f,   0,     {"-",  "-"         },   " "    }, 
    { 1,      1,      "二次变比_U0",     &g_Parameter[RATIO_U0_SECONDARY],           "V",     1000.00f,   0.00f,    0,     {"-",  "-"         },   " "    },
    { 1,      1,      "一次变比_I",      &g_Parameter[RATIO_I_ONE_TURN],             "A",    100000.00f,   0.00f,   0,     {"-",  "-"         },   " "    }, 
    { 1,      1,      "二次变比_I",      &g_Parameter[RATIO_I_SECONDARY],            "A",     1000.00f,   0.00f,    0,     {"-",  "-"         },   " "    },	
    { 1,      1,      "一次变比_I0",     &g_Parameter[RATIO_I0_ONE_TURN],            "A",     10000.00f,   0.00f,   0,     {"-",  "-"         },   " "    }, 
    { 1,      1,      "二次变比_I0",     &g_Parameter[RATIO_I0_SECONDARY],           "A",     10000.00f,   0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      1,      "开入防抖时间",    &g_Parameter[DI_SHAKING_TIME],              "ms",     99999,        0,     0,     {"-",  "-"         },   " "    },	
    { 1,      1,      "合闸脉宽时间",    &g_Parameter[CLOSING_PULSE_TIME],           "ms",     99999,        0,     0,     {"-",  "-"         },   " "    },
    { 1,      1,      "分闸脉宽时间",    &g_Parameter[OPENING_PULSE_TIME],           "ms",     99999,        0,     0,     {"-",  "-"         },   " "    },	
    { 1,      1,      "反校时间",        &g_Parameter[REVERSE_TIME],                 "ms",     99999,        0,     0,     {"-",  "-"         },   " "    },	
 
    { 1,      2,      "频率零漂",        &g_Parameter[ZERODRIFT_F],                 "Hz",     99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "A相电流零漂",     &g_Parameter[ZERODRIFT_Ia],                "A",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "B相电流零漂",     &g_Parameter[ZERODRIFT_Ib],                "A",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "C相电流零漂",     &g_Parameter[ZERODRIFT_Ic],                "A",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "零序电流零漂",    &g_Parameter[ZERODRIFT_I0],                "A",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      2,      "Uab零漂",         &g_Parameter[ZERODRIFT_Uab],               "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "Ubc零漂",         &g_Parameter[ZERODRIFT_Ubc],               "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      2,      "Uac零漂",         &g_Parameter[ZERODRIFT_Uac],               "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "U0零漂",          &g_Parameter[ZERODRIFT_U0],                "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      2,      "UAB零漂",         &g_Parameter[ZERODRIFT_UAB],               "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "UBC零漂",         &g_Parameter[ZERODRIFT_UBC],               "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "有功功率零漂",    &g_Parameter[ZERODRIFT_P],                 "kW",     99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "无功功率零漂",    &g_Parameter[ZERODRIFT_Q],                 "kVar",   99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "视在功率零漂",    &g_Parameter[ZERODRIFT_S],                 "kVA",    99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      2,      "功率因数零漂",    &g_Parameter[ZERODRIFT_PF],                "-",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "直流1零漂",       &g_Parameter[ZERODRIFT_DC1],               "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "直流2零漂",       &g_Parameter[ZERODRIFT_DC2],               "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      2,      "温度零漂",        &g_Parameter[ZERODRIFT_T],                 "°C",     99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
	
    { 1,      3,      "频率死区",        &g_Parameter[DEADZONE_F],                   "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "A相电流死区",     &g_Parameter[DEADZONE_Ia],                  "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "B相电流死区",     &g_Parameter[DEADZONE_Ib],                  "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "C相电流死区",     &g_Parameter[DEADZONE_Ic],                  "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "零序电流死区",    &g_Parameter[DEADZONE_I0],                  "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      3,      "Uab死区",         &g_Parameter[DEADZONE_Uab],                 "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "Ubc死区",         &g_Parameter[DEADZONE_Ubc],                 "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      3,      "Uac死区",         &g_Parameter[DEADZONE_Uac],                 "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "U0死区",          &g_Parameter[DEADZONE_U0],                  "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      3,      "UAB死区",         &g_Parameter[DEADZONE_UAB],                 "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "UBC死区",         &g_Parameter[DEADZONE_UBC],                 "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "有功功率死区",    &g_Parameter[DEADZONE_P],                   "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "无功功率死区",    &g_Parameter[DEADZONE_Q],                   "%",      99.99f,     0.01f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "视在功率死区",    &g_Parameter[DEADZONE_S],                   "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      3,      "功率因数死区",    &g_Parameter[DEADZONE_PF],                  "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "直流1死区",       &g_Parameter[DEADZONE_DC1],                 "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "直流2死区",       &g_Parameter[DEADZONE_DC2],                 "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      3,      "温度死区",        &g_Parameter[DEADZONE_T],                   "%",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
}; 

/* 定值一区 */
struct tagValueParaCfg FixedValueCfg1[] = 
{
//   使能  菜单编号       名称                            值                           单位       上限        下限   数据类型     显示内容           备注
    { 1,      1,      "过流一段投退",    &g_FixedValue1[OVER_CURRENT_SWITCH1],          "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      1,      "过流一段电流",    &g_FixedValue1[OVER_CURRENT_VALUE1],           "A",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      1,      "过流一段时间",    &g_FixedValue1[OVER_CURRENT_TIME1],            "S",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      1,      "过流二段投退",    &g_FixedValue1[OVER_CURRENT_SWITCH2],          "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      1,      "过流二段电流",    &g_FixedValue1[OVER_CURRENT_VALUE2],           "A",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      1,      "过流二段时间",    &g_FixedValue1[OVER_CURRENT_TIME2],            "S",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      1,      "过流三段投退",    &g_FixedValue1[OVER_CURRENT_SWITCH3],          "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      1,      "过流三段电流",    &g_FixedValue1[OVER_CURRENT_VALUE3],           "A",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      1,      "过流三段时间",    &g_FixedValue1[OVER_CURRENT_TIME3],            "S",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      2,      "零序一段投退",    &g_FixedValue1[OVER_CURRENTI0_SWITCH1],        "-",       1,           0,     3,     {"退", "投", "告警"},   " "   },    
    { 1,      2,      "零序一段电流",    &g_FixedValue1[OVER_CURRENTI0_VALUE1],         "A",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      2,      "零序一段时间",    &g_FixedValue1[OVER_CURRENTI0_TIME1],          "S",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      2,      "零序二段投退",    &g_FixedValue1[OVER_CURRENTI0_SWITCH2],        " ",       1,           0,     3,     {"退", "投", "告警"},   " "    },    
    { 1,      2,      "零序二段电流",    &g_FixedValue1[OVER_CURRENTI0_VALUE2],         "A",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "    }, 
    { 1,      2,      "零序二段时间",    &g_FixedValue1[OVER_CURRENTI0_TIME2],          "S",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "越限告警投退",    &g_FixedValue1[OVERLIMIT_SWITCH],              "-",       1,           0,     2,     {"退", "投"        },   " "    },
    { 1,      5,      "越限上限系数",    &g_FixedValue1[UPLIMIT_FACTOR],                "-",     1.00f,       0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "越限下限系数",    &g_FixedValue1[DOWNLIMIT_FACTOR],              "-",     2.00f,       1.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      5,      "越限延时",        &g_FixedValue1[OVERLIMIT_TIME],                "S",     999.99f,       0,     0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "Uab越限投退",     &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_Uab],    "-",       1,           0,     2,     {"退", "投"        },   " "    },
    { 1,      5,      "UBC越限投退",     &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_UBC],    "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "Uac越限投退",     &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_Uac],    "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "电压上限定值",    &g_FixedValue1[UPLIMIT_VOLTAGE_U],             "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "电压下限定值",    &g_FixedValue1[DOWNLIMIT_VOLTAGE_U],           "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "Ia越限投退",      &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_IA],     "-",       1,           0,     2,     {"退", "投"        },   " "    },
    { 1,      5,      "Ib越限投退",      &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_IB],     "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "Ic越限投退",      &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_IC],     "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "电流上限定值",    &g_FixedValue1[UPLIMIT_CURRENT_I],             "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "电流下限定值",    &g_FixedValue1[DOWNLIMIT_CURRENT_I],           "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "U0越限投退",      &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_U0],     "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "U0上限定值",      &g_FixedValue1[UPLIMIT_VOLTAGE_U0],            "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "U0下限定值",      &g_FixedValue1[DOWNLIMIT_VOLTAGE_U0],          "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      5,      "I0越限投退",      &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_I0],     "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "I0上限定值",      &g_FixedValue1[UPLIMIT_VOLTAGE_I0],            "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "I0下限定值",      &g_FixedValue1[DOWNLIMIT_VOLTAGE_I0],          "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      5,      "U_DC越限投退",    &g_FixedValue1[OVERLIMIT_ALARMSWITCH_DC_U],    "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "U_DC上限定值",    &g_FixedValue1[UPLIMIT_DC_VOLTAGE_U],          "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "U_DC下限定值",    &g_FixedValue1[DOWNLIMIT_DC_VOLTAGE_U],        "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      5,      "I_DC越限投退",    &g_FixedValue1[OVERLIMIT_ALARMSWITCH_DC_I],    "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "I_DC上限定值",    &g_FixedValue1[UPLIMIT_DC_CURRENT_I],          "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "I_DC下限定值",    &g_FixedValue1[DOWNLIMIT_DC_CURRENT_I],        "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      6,      "重过载投退",      &g_FixedValue1[HEAVY_OVERLOAD_SWITCH],         "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      6,      "重过载定值",      &g_FixedValue1[HEAVY_OVERLOAD_VALUE],          "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      6,      "重过载系数",      &g_FixedValue1[HEAVY_OVERLOAD_FACTOR],         "-",      1.00f,      0.01f,   0,     {"-",  "-"         },   " "    },	
    { 1,      6,      "重过载延时",      &g_FixedValue1[HEAVY_OVERLOAD_TIME],           "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      6,      "过负荷投退",      &g_FixedValue1[OVERLOAD_SWITCH],               "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      6,      "过负荷定值",      &g_FixedValue1[OVERLOAD_VALUE],                "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      6,      "过负荷系数",      &g_FixedValue1[OVERLOAD_FACTOR],               "-",      1.00f,      0.01f,   0,     {"-",  "-"         },   " "    },	
    { 1,      6,      "过负荷延时",      &g_FixedValue1[OVERLOAD_TIME],                 "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      9,      "低压告警投退",    &g_FixedValue1[BATTERY_LOWVOLTAGE_ALARM_SWITCH],"-",       1,          0,     2,     {"退", "投"        },   " "    },	
    { 1,      9,      "电池低压定值",    &g_FixedValue1[BATTERY_LOWVOLTAGE_VALUE],      "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      9,      "电池低压系数",    &g_FixedValue1[BATTERY_LOWVOLTAGE_FACTOR],     "-",      2.00f,      1.01f,   0,     {"-",  "-"         },   " "    },	
    { 1,      9,      "电池低压延时",    &g_FixedValue1[BATTERY_LOWVOLTAGE_TIME],       "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      9,      "电池活化投退",    &g_FixedValue1[BATTERY_ACTIVE_SWITCH],         "-",        1,          0,     2,     {"退", "投"        },   " "    },	
    { 1,      9,      "电池活化周期",    &g_FixedValue1[BATTERY_ACTIVE_CYCLE],          "天",    99999.99f,   0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      9,      "活化持续时间",    &g_FixedValue1[BATTERY_ACTIVE_TIME],           "h",       23,          0,     0,     {"-",  "-"         },   " "    },	
    { 1,      9,      "活化故障电压",    &g_FixedValue1[BATTERY_ACTIVE_FAULT_VOLTAGE],  "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      9,      "活化故障延时",    &g_FixedValue1[BATTERY_ACTIVE_FAULT_TIME],     "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,     10,      "自动复归投退",    &g_FixedValue1[AUTOMATIC_RESET_SWITCH],        "-",        1,          0,     2,     {"退", "投"        },   " "    },	
    { 1,     10,      "自动复归延时",    &g_FixedValue1[AUTOMATIC_RESET_TIME],          "S",     99999.99f,   0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过电压投退",      &g_FixedValue1[OVERVOLTAGE_SWITCH],            "-",       1,           0,     3,     {"退", "投", "告警"},   " "    },	
    { 1,      8,      "过电压定值",      &g_FixedValue1[OVERVOLTAGE_VALUE],             "V",     9999.99f,    0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过电压延时",      &g_FixedValue1[OVERVOLTAGE_TIME],              "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过电压系数",      &g_FixedValue1[OVERVOLTAGE_FACTOR],            "-",      1.00f,      0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过频投退",        &g_FixedValue1[OVERFREQUENCY_SWITCH],          "-",       1,           0,     3,     {"退", "投", "告警"},   " "    },	
    { 1,      8,      "过频定值",        &g_FixedValue1[OVERFREQUENCY_VALUE],           "Hz",     99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过频延时",        &g_FixedValue1[OVERFREQUENCY_TIME],            "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过频系数",        &g_FixedValue1[OVERFREQUENCY_FACTOR],          "-",      1.00f,      0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      8,      "低电压投退",      &g_FixedValue1[DOWNVOLTAGE_SWITCH],            "-",       1,           0,     3,     {"退", "投", "告警"},   " "    },	
    { 1,      8,      "低电压定值",      &g_FixedValue1[DOWNVOLTAGE_VALUE],             "V",     99999.99f,   0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "低电压延时",      &g_FixedValue1[DOWNVOLTAGE_TIME],              "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "低电压系数",      &g_FixedValue1[DOWNVOLTAGE_FACTOR],            "-",      2.00f,      1.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "低频投退",        &g_FixedValue1[DOWNFREQUENCY_SWITCH],          "-",       1,           0,     3,     {"退", "投", "告警"},   " "    },	
    { 1,      8,      "低频定值",        &g_FixedValue1[DOWNFREQUENCY_VALUE],           "Hz",     99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "低频延时",        &g_FixedValue1[DOWNFREQUENCY_TIME],            "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "低频系数",        &g_FixedValue1[DOWNFREQUENCY_FACTOR],          "-",      2.00f,      1.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      8,      "合环投退",        &g_FixedValue1[CLOSING_LOOP_SWITCH],           "-",       1,           0,     2,     {"退", "投",       },   " "    },	
    { 1,      8,      "两侧压差",        &g_FixedValue1[VOLTAGE_DIFFERENCE],            "V",      30.00f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "相角差",          &g_FixedValue1[PHASEANGLE_DIFFERENCE],         "°",      10.00f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "控制回路异常",    &g_FixedValue1[CONTROL_LOOP_ANOMALY_ENABLE],   "-",       1,           0,     2,     {"退", "投",       },   " "    },		
    { 1,      3,      "反时限投退",      &g_FixedValue1[INVERSE_SWITCH],                "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      3,      "反时限定值",      &g_FixedValue1[INVERSE_CURRENT_VALUE],         "A",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      3,      "反时限延时",      &g_FixedValue1[INVERSE_TIME],                  "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      3,      "后加速投退",      &g_FixedValue1[IACC_SWITCH],                   "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      3,      "后加速定值",      &g_FixedValue1[IACC_CURRENT_VALUE],            "A",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      3,      "后加速延时",      &g_FixedValue1[IACC_TIME],                     "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "涌流抑制投退",    &g_FixedValue1[INRUSH_SWITCH],                 "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      3,      "涌流抑制延时",    &g_FixedValue1[INRUSH_TIME],                   "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      3,      "二次重合闭锁",    &g_FixedValue1[SECONDARY_RECLOSE_LOCK_SWITCH], "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      3,      "重合闭锁时间",    &g_FixedValue1[SECONDARY_RECLOSE_LOCK_TIME],   "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "相间重合次数",    &g_FixedValue1[RECLOSE_TIMES_I],               "次",      4,           0,     0,     {"-",  "-"         },   " "   },
    { 1,      3,      "零序重合次数",    &g_FixedValue1[RECLOSE_TIMES_I0],              "次",      2,           0,     0,     {"-",  "-"         },   " "   },
    { 1,      3,      "一次重合时间",    &g_FixedValue1[RECLOSE_TIMER1],                "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "二次重合时间",    &g_FixedValue1[RECLOSE_TIMER2],                "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "三次重合时间",    &g_FixedValue1[RECLOSE_TIMER3],                "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "四次重合时间",    &g_FixedValue1[RECLOSE_TIMER4],                "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      3,      "重合复位时间",    &g_FixedValue1[RE_RESET_TIME],                 "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "重合充电时间",    &g_FixedValue1[RE_CHARGE_TIME],                "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      4,      "有流定值",        &g_FixedValue1[CURRENT_VALUE],                 "I",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      4,      "有压定值",        &g_FixedValue1[VOLTAGE_VALUE],                 "V",     9999.99f,    0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      4,      "Y时限",           &g_FixedValue1[FAULT_CHECK_Y_TIME],            "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      4,      "闭锁分闸时间",    &g_FixedValue1[SHORT_LOCKED_OPENING_TIME],     "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    

    { 1,      4,      "失电分闸投退",    &g_FixedValue1[LOSS_ELECTRICITY_SWITCH],       "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      4,      "失电分闸时间",    &g_FixedValue1[LOSS_OPENING_TIME],             "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },		
    { 1,      4,      "得电合闸投退",    &g_FixedValue1[GET_VOLTAGE_CLOSSING_SWITCH],   "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      4,      "得电合闸时间",    &g_FixedValue1[GET_VOLTAGE_CLOSSING_X_TIME],   "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      4,      "单侧失压合闸",    &g_FixedValue1[SINGLE_LOSS_VOLTAGE_SWITCH],    "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      4,      "单侧失压时间",    &g_FixedValue1[SINGLE_LOSS_VOLTAGE_TIME],      "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      4,      "双侧有压投退",    &g_FixedValue1[DOUBLE_VOLTAGE_SWITCH],         "-",       1,           0,     2,     {"退", "投"        },   " "   },  
    { 1,      4,      "残压脉冲投退",    &g_FixedValue1[REMAIN_VOLTAGE_SWITCH],         "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      4,      "残压整定电压",    &g_FixedValue1[REMAIN_VOLTAGE_VALUE],          "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      4,      "U0保护投退",      &g_FixedValue1[VOLTAGE_U0_SWITCH],             "-",       1,           0,     2,     {"退", "投",       },   " "    },	
    { 1,      4,      "U0保护电压",      &g_FixedValue1[VOLTAGE_U0_VALUE],              "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      4,      "U0保护延时",      &g_FixedValue1[VOLTAGE_U0_TIME],               "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      4,      "非遮断投退",      &g_FixedValue1[BREAKING_CURRENT_SWITCH],       "-",       1,           0,     2,     {"退", "投",       },   " "    },	
    { 1,      4,      "非遮断电流",      &g_FixedValue1[BREAKING_CURRENT_VALUE],        "I",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
}; 

/* 定值二区 */
struct tagValueParaCfg FixedValueCfg2[] = 
{
//   使能  菜单编号       名称                            值                           单位       上限        下限   数据类型     显示内容           备注
    { 1,      1,      "过流一段投退",    &g_FixedValue2[OVER_CURRENT_SWITCH1],          "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      1,      "过流一段电流",    &g_FixedValue2[OVER_CURRENT_VALUE1],           "A",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      1,      "过流一段时间",    &g_FixedValue2[OVER_CURRENT_TIME1],            "S",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   },	

    { 1,      1,      "过流二段投退",    &g_FixedValue2[OVER_CURRENT_SWITCH2],          "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      1,      "过流二段电流",    &g_FixedValue2[OVER_CURRENT_VALUE2],           "A",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      1,      "过流二段时间",    &g_FixedValue2[OVER_CURRENT_TIME2],            "S",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   },	

    { 1,      1,      "过流三段投退",    &g_FixedValue2[OVER_CURRENT_SWITCH3],          "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      1,      "过流三段电流",    &g_FixedValue2[OVER_CURRENT_VALUE3],           "A",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      1,      "过流三段时间",    &g_FixedValue2[OVER_CURRENT_TIME3],            "S",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   },	

    { 1,      2,      "零序一段投退",    &g_FixedValue2[OVER_CURRENTI0_SWITCH1],        "-",       1,           0,     3,     {"退", "投", "告警"},   " "   },    
    { 1,      2,      "零序一段电流",    &g_FixedValue2[OVER_CURRENTI0_VALUE1],         "A",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      2,      "零序一段时间",    &g_FixedValue2[OVER_CURRENTI0_TIME1],          "S",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    
    { 1,      2,      "零序二段投退",    &g_FixedValue2[OVER_CURRENTI0_SWITCH2],        " ",       1,           0,     3,     {"退", "投", "告警"},   " "    },    
    { 1,      2,      "零序二段电流",    &g_FixedValue2[OVER_CURRENTI0_VALUE2],         "A",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "    }, 
    { 1,      2,      "零序二段时间",    &g_FixedValue2[OVER_CURRENTI0_TIME2],          "S",     100.00f,     0.00f,   0,     {"-",  "-"         },   " "    },	

    { 1,      5,      "越限告警投退",    &g_FixedValue2[OVERLIMIT_SWITCH],              "-",       1,           0,     2,     {"退", "投"        },   " "    },
    { 1,      5,      "越限上限系数",    &g_FixedValue2[UPLIMIT_FACTOR],                "-",     1.00f,       0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "越限下限系数",    &g_FixedValue2[DOWNLIMIT_FACTOR],              "-",     2.00f,       1.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      5,      "越限延时",        &g_FixedValue2[OVERLIMIT_TIME],                "S",     999.99f,       0,     0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "Uab越限投退",     &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_Uab],    "-",       1,           0,     2,     {"退", "投"        },   " "    },
    { 1,      5,      "UBC越限投退",     &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_UBC],    "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "Uac越限投退",     &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_Uac],    "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "电压上限定值",    &g_FixedValue2[UPLIMIT_VOLTAGE_U],             "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "电压下限定值",    &g_FixedValue2[DOWNLIMIT_VOLTAGE_U],           "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "Ia越限投退",      &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_IA],     "-",       1,           0,     2,     {"退", "投"        },   " "    },
    { 1,      5,      "Ib越限投退",      &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_IB],     "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "Ic越限投退",      &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_IC],     "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "电流上限定值",    &g_FixedValue2[UPLIMIT_CURRENT_I],             "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "电流下限定值",    &g_FixedValue2[DOWNLIMIT_CURRENT_I],           "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "U0越限投退",      &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_U0],     "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "U0上限定值",      &g_FixedValue2[UPLIMIT_VOLTAGE_U0],            "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "U0下限定值",      &g_FixedValue2[DOWNLIMIT_VOLTAGE_U0],          "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      5,      "I0越限投退",      &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_I0],     "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "I0上限定值",      &g_FixedValue2[UPLIMIT_VOLTAGE_I0],            "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "I0下限定值",      &g_FixedValue2[DOWNLIMIT_VOLTAGE_I0],          "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      5,      "U_DC越限投退",    &g_FixedValue2[OVERLIMIT_ALARMSWITCH_DC_U],    "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "U_DC上限定值",    &g_FixedValue2[UPLIMIT_DC_VOLTAGE_U],          "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "U_DC下限定值",    &g_FixedValue2[DOWNLIMIT_DC_VOLTAGE_U],        "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      5,      "I_DC越限投退",    &g_FixedValue2[OVERLIMIT_ALARMSWITCH_DC_I],    "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      5,      "I_DC上限定值",    &g_FixedValue2[UPLIMIT_DC_CURRENT_I],          "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      5,      "I_DC下限定值",    &g_FixedValue2[DOWNLIMIT_DC_CURRENT_I],        "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      6,      "重过载投退",      &g_FixedValue2[HEAVY_OVERLOAD_SWITCH],         "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      6,      "重过载定值",      &g_FixedValue2[HEAVY_OVERLOAD_VALUE],          "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      6,      "重过载系数",      &g_FixedValue2[HEAVY_OVERLOAD_FACTOR],         "-",      1.00f,      0.01f,   0,     {"-",  "-"         },   " "    },	
    { 1,      6,      "重过载延时",      &g_FixedValue2[HEAVY_OVERLOAD_TIME],           "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      6,      "过负荷投退",      &g_FixedValue2[OVERLOAD_SWITCH],               "-",       1,           0,     2,     {"退", "投"        },   " "    },	
    { 1,      6,      "过负荷定值",      &g_FixedValue2[OVERLOAD_VALUE],                "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      6,      "过负荷系数",      &g_FixedValue2[OVERLOAD_FACTOR],               "-",      1.00f,      0.01f,   0,     {"-",  "-"         },   " "    },	
    { 1,      6,      "过负荷延时",      &g_FixedValue2[OVERLOAD_TIME],                 "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      9,      "低压告警投退",    &g_FixedValue2[BATTERY_LOWVOLTAGE_ALARM_SWITCH],"-",       1,          0,     2,     {"退", "投"        },   " "    },	
    { 1,      9,      "电池低压定值",    &g_FixedValue2[BATTERY_LOWVOLTAGE_VALUE],      "A",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      9,      "电池低压系数",    &g_FixedValue2[BATTERY_LOWVOLTAGE_FACTOR],     "-",      2.00f,      1.01f,   0,     {"-",  "-"         },   " "    },	
    { 1,      9,      "电池低压延时",    &g_FixedValue2[BATTERY_LOWVOLTAGE_TIME],       "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      9,      "电池活化投退",    &g_FixedValue2[BATTERY_ACTIVE_SWITCH],         "-",        1,          0,     2,     {"退", "投"        },   " "    },	
    { 1,      9,      "电池活化周期",    &g_FixedValue2[BATTERY_ACTIVE_CYCLE],          "天",    99999.99f,   0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      9,      "活化持续时间",    &g_FixedValue2[BATTERY_ACTIVE_TIME],           "h",       23,          0,     0,     {"-",  "-"         },   " "    },	
    { 1,      9,      "活化故障电压",    &g_FixedValue2[BATTERY_ACTIVE_FAULT_VOLTAGE],  "V",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      9,      "活化故障延时",    &g_FixedValue2[BATTERY_ACTIVE_FAULT_TIME],     "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,     10,      "自动复归投退",    &g_FixedValue2[AUTOMATIC_RESET_SWITCH],        "-",        1,          0,     2,     {"退", "投"        },   " "    },	
    { 1,     10,      "自动复归延时",    &g_FixedValue2[AUTOMATIC_RESET_TIME],          "S",     99999.99f,   0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过电压投退",      &g_FixedValue2[OVERVOLTAGE_SWITCH],            "-",       1,           0,     3,     {"退", "投", "告警"},   " "    },	
    { 1,      8,      "过电压定值",      &g_FixedValue2[OVERVOLTAGE_VALUE],             "V",     9999.99f,    0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过电压延时",      &g_FixedValue2[OVERVOLTAGE_TIME],              "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过电压系数",      &g_FixedValue2[OVERVOLTAGE_FACTOR],            "-",      1.00f,      0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过频投退",        &g_FixedValue2[OVERFREQUENCY_SWITCH],          "-",       1,           0,     3,     {"退", "投", "告警"},   " "    },	
    { 1,      8,      "过频定值",        &g_FixedValue2[OVERFREQUENCY_VALUE],           "Hz",     99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过频延时",        &g_FixedValue2[OVERFREQUENCY_TIME],            "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "过频系数",        &g_FixedValue2[OVERFREQUENCY_FACTOR],          "-",      1.00f,      0.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      8,      "低电压投退",      &g_FixedValue2[DOWNVOLTAGE_SWITCH],            "-",       1,           0,     3,     {"退", "投", "告警"},   " "    },	
    { 1,      8,      "低电压定值",      &g_FixedValue2[DOWNVOLTAGE_VALUE],             "V",     99999.99f,   0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "低电压延时",      &g_FixedValue2[DOWNVOLTAGE_TIME],              "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "低电压系数",      &g_FixedValue2[DOWNVOLTAGE_FACTOR],            "-",      2.00f,      1.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "低频投退",        &g_FixedValue2[DOWNFREQUENCY_SWITCH],          "-",       1,           0,     3,     {"退", "投", "告警"},   " "    },	
    { 1,      8,      "低频定值",        &g_FixedValue2[DOWNFREQUENCY_VALUE],           "Hz",     99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "低频延时",        &g_FixedValue2[DOWNFREQUENCY_TIME],            "S",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "低频系数",        &g_FixedValue2[DOWNFREQUENCY_FACTOR],          "-",      2.00f,      1.00f,   0,     {"-",  "-"         },   " "    },		
    { 1,      8,      "合环投退",        &g_FixedValue2[CLOSING_LOOP_SWITCH],           "-",       1,           0,     2,     {"退", "投",       },   " "    },	
    { 1,      8,      "两侧压差",        &g_FixedValue2[VOLTAGE_DIFFERENCE],            "V",      30.00f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "相角差",          &g_FixedValue2[PHASEANGLE_DIFFERENCE],         "°",      10.00f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      8,      "控制回路异常",    &g_FixedValue2[CONTROL_LOOP_ANOMALY_ENABLE],   "-",       1,           0,     2,     {"退", "投",       },   " "    },		
    { 1,      3,      "反时限投退",      &g_FixedValue2[INVERSE_SWITCH],                "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      3,      "反时限定值",      &g_FixedValue2[INVERSE_CURRENT_VALUE],         "A",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      3,      "反时限延时",      &g_FixedValue2[INVERSE_TIME],                  "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      3,      "后加速投退",      &g_FixedValue2[IACC_SWITCH],                   "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      3,      "后加速定值",      &g_FixedValue2[IACC_CURRENT_VALUE],            "A",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   }, 
    { 1,      3,      "后加速延时",      &g_FixedValue2[IACC_TIME],                     "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "涌流抑制投退",    &g_FixedValue2[INRUSH_SWITCH],                 "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      3,      "涌流抑制延时",    &g_FixedValue2[INRUSH_TIME],                   "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      3,      "二次重合闭锁",    &g_FixedValue2[SECONDARY_RECLOSE_LOCK_SWITCH], "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      3,      "重合闭锁时间",    &g_FixedValue2[SECONDARY_RECLOSE_LOCK_TIME],   "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "相间重合次数",    &g_FixedValue2[RECLOSE_TIMES_I],               "次",      4,           0,     0,     {"-",  "-"         },   " "   },
    { 1,      3,      "零序重合次数",    &g_FixedValue2[RECLOSE_TIMES_I0],              "次",      2,           0,     0,     {"-",  "-"         },   " "   },
    { 1,      3,      "一次重合时间",    &g_FixedValue2[RECLOSE_TIMER1],                "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "二次重合时间",    &g_FixedValue2[RECLOSE_TIMER2],                "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "三次重合时间",    &g_FixedValue2[RECLOSE_TIMER3],                "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "四次重合时间",    &g_FixedValue2[RECLOSE_TIMER4],                "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      3,      "重合复位时间",    &g_FixedValue2[RE_RESET_TIME],                 "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      3,      "重合充电时间",    &g_FixedValue2[RE_CHARGE_TIME],                "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },

    { 1,      4,      "有流定值",        &g_FixedValue2[CURRENT_VALUE],                 "I",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      4,      "有压定值",        &g_FixedValue2[VOLTAGE_VALUE],                 "V",     9999.99f,    0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      4,      "Y时限",           &g_FixedValue2[FAULT_CHECK_Y_TIME],            "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      4,      "闭锁分闸时间",    &g_FixedValue2[SHORT_LOCKED_OPENING_TIME],     "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },
    { 1,      4,      "失电分闸投退",    &g_FixedValue2[LOSS_ELECTRICITY_SWITCH],       "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      4,      "失电分闸时间",    &g_FixedValue2[LOSS_OPENING_TIME],             "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },		
    { 1,      4,      "得电合闸投退",    &g_FixedValue2[GET_VOLTAGE_CLOSSING_SWITCH],   "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      4,      "得电合闸时间",    &g_FixedValue2[GET_VOLTAGE_CLOSSING_X_TIME],   "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      4,      "单侧失压合闸",    &g_FixedValue2[SINGLE_LOSS_VOLTAGE_SWITCH],    "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      4,      "单侧失压时间",    &g_FixedValue2[SINGLE_LOSS_VOLTAGE_TIME],      "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      4,      "双侧有压投退",    &g_FixedValue2[DOUBLE_VOLTAGE_SWITCH],         "-",       1,           0,     2,     {"退", "投"        },   " "   },  
    { 1,      4,      "残压脉冲投退",    &g_FixedValue2[REMAIN_VOLTAGE_SWITCH],         "-",       1,           0,     2,     {"退", "投"        },   " "   },    
    { 1,      4,      "残压整定电压",    &g_FixedValue2[REMAIN_VOLTAGE_VALUE],          "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "   },	
    { 1,      4,      "U0保护投退",      &g_FixedValue2[VOLTAGE_U0_SWITCH],             "-",       1,           0,     2,     {"退", "投",       },   " "    },	
    { 1,      4,      "U0保护电压",      &g_FixedValue2[VOLTAGE_U0_VALUE],              "V",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },	
    { 1,      4,      "U0保护延时",      &g_FixedValue2[VOLTAGE_U0_TIME],               "S",      99.99f,     0.00f,   0,     {"-",  "-"         },   " "    },
    { 1,      4,      "非遮断投退",      &g_FixedValue2[BREAKING_CURRENT_SWITCH],       "-",       1,           0,     2,     {"退", "投",       },   " "    },	
    { 1,      4,      "非遮断电流",      &g_FixedValue2[BREAKING_CURRENT_VALUE],        "I",     999.99f,     0.00f,   0,     {"-",  "-"         },   " "    },		
}; 


unsigned int g_FixedValueCfg1_Len = sizeof(FixedValueCfg1) / sizeof(FixedValueCfg1[0]);
unsigned int g_FixedValueCfg2_Len = sizeof(FixedValueCfg2) / sizeof(FixedValueCfg2[0]);
unsigned int g_ParameterCfg_Len = sizeof(ParameterCfg) / sizeof(ParameterCfg[0]);
unsigned int g_CalibrateFactorCfg_Len = sizeof(CalibrateFactorCfg) / sizeof(CalibrateFactorCfg[0]);
unsigned int g_TelemetryCfg_Len = sizeof(TelemetryCfg) / sizeof(TelemetryCfg[0]);
unsigned int g_TelesignalCfg_Len = sizeof(TelesignalCfg) / sizeof(TelesignalCfg[0]);

/* END OF FILE ---------------------------------------------------------------*/


