/**
  *             Copyright (C) SOJO Electric CO., Ltd. 2017-2018. All right reserved.
  * @file:      point_table_config.c
  * @brief:     The point_table_config  of the project.
  * @version:   ver 1.1
  * @author:    Mr.Sun
  * @date:      2018-05-09
  * @update:    [2018-05-09][name][change]
  */
	
	
/* INCLUDES FILES ------------------------------------------------------------*/
#include "common_data.h"
#include "point_table_config.h"


/* 遥信 */
struct tagTelesignalCfg TelesignalCfg[] = 
{
//   使能    名称	                      遥信                                           描述
    { 1,  "开关分位",            &g_TelesignalDB[ADDR_OPEN],                         {"分", "合"},      {"合->分","分->合"}},
    { 1,  "开关合位",            &g_TelesignalDB[ADDR_CLOSE],                        {"分", "合"},      {"合->分","分->合"}},
    { 1,  "储能有压",            &g_TelesignalDB[ADDR_OPERATING_MECHANISM],          {"无", "有"},      {"有->无","无->有"}},
    { 1,  "低气压",              &g_TelesignalDB[ADDR_LOW_PRESSURE],                 {"无", "告警"},    {"告警->复位","无->告警"}},
    { 1,  "电源故障告警",        &g_TelesignalDB[ADDR_POWERFAULTALARM],              {"无", "告警"},    {"告警->复位","无->告警"}},
    { 1,  "电池欠压告警",        &g_TelesignalDB[ADDR_BATTERY_UNDERVOLTAGE_ALARM],   {"无", "告警"},    {"告警->复位","无->告警"}},
    { 1,  "电池活化状态",        &g_TelesignalDB[ADDR_BATTERYACTIVATIONSTATUS],      {"无", "活化"},    {"活化->结束","开始活化"}},
    { 1,  "电池失电告警",        &g_TelesignalDB[ADDR_BATTERY_LOSS_ALARM],           {"无", "告警"},    {"告警->复位","无->告警"}},
    { 1,  "工作模式",            &g_TelesignalDB[ADDR_BREAK_CONTACT],                {"分段", "联络"},  {"联络->分段","分段->联络"}},
    { 1,  "重合压板/FA",         &g_TelesignalDB[ADDR_RECLOSE_FA_STRAP],             {"退出", "投入"},  {"投->退","退->投"}},
    { 1,  "保护压板",            &g_TelesignalDB[ADDR_FUNCTION_HARDSTRAP],           {"退出", "投入"},  {"投->退","退->投"}},
    { 1,  "远方/就地",           &g_TelesignalDB[ADDR_REMOTE_EARTH],                 {"远方", "就地"},  {"远方->就地","就地->远方"}},
    { 1,  "短路故障",            &g_TelesignalDB[ADDR_SHORT_CIRCUIT_FAULT],          {"复位","保护"},   {"复位","保护"}},
    { 1,  "零序故障",            &g_TelesignalDB[ADDR_EARTHING_FAULT],               {"复位","保护"},   {"复位","保护"}},
    { 1,  "保护动作",            &g_TelesignalDB[ADDR_PROTECTION_ACT],               {"复位","动作"},   {"复位","动作"}},
    { 1,  "保护闭锁",            &g_TelesignalDB[ADDR_PROTECTION_LOCK],              {"复位","闭锁"},   {"复位","闭锁"}},
    { 1,  "合闸闭锁",            &g_TelesignalDB[ADDR_CLOSING_LOCK],                 {"复位","闭锁"},   {"复位","闭锁"}},	
    { 1,  "分闸闭锁",            &g_TelesignalDB[ADDR_OPENING_LOCK],                 {"复位","闭锁"},   {"复位","闭锁"}},
    { 1,  "重合动作",            &g_TelesignalDB[ADDR_RECLOSE_ACT],                  {"复位","动作"},   {"复位","动作"}},
    { 1,  "重合闭锁",            &g_TelesignalDB[ADDR_RECLOSE_LOCK],                 {"复位","闭锁"},   {"复位","闭锁"}},
    { 1,  "装置故障",            &g_TelesignalDB[ADDR_DEVICE_FAULT],                 {"无","故障"},     {"无","故障"}},
    { 1,  "自检异常",            &g_TelesignalDB[ADDR_SELF_CHECK_ABNOMAL],           {"无","异常"},     {"无","异常"}},
    { 1,  "通讯",                &g_TelesignalDB[ADDR_COMMUNICATION],                {"断","通"},       {"断","通"}},
    { 1,  "开关类型",            &g_TelesignalDB[ADDR_SWTICHCLASS],                  {"断路器","负荷开关"}, {"断路器","负荷开关"}},	
    { 1,  "电池故障告警",        &g_TelesignalDB[ADDR_BATTERY_FAULT_ALARM],          {"无","告警"},     {"无","告警"}},
    { 1,  "双点开关分合",        &g_TelesignalDB[ADDR_DOUBLE_SWITCH],                {"合->分","分->合"}, {"合->分","分->合"}}, 
    { 1,  "控制回路断线",        &g_TelesignalDB[ADDR_CONTROL_LOOP_DISCONNECTION],   {"复位","断线"},   {"复位","断线"}},
    { 1,  "A相过流一段",         &g_TelesignalDB[ADDR_OVERCURRENT_IA_1],             {"复位","保护"},   {"复位","保护"}},
    { 1,  "B相过流一段",         &g_TelesignalDB[ADDR_OVERCURRENT_IB_1],             {"复位","保护"},   {"复位","保护"}},	
    { 1,  "C相过流一段",         &g_TelesignalDB[ADDR_OVERCURRENT_IC_1],             {"复位","保护"},   {"复位","保护"}},
    { 1,  "A相过流二段",         &g_TelesignalDB[ADDR_OVERCURRENT_IA_2],             {"复位","保护"},   {"复位","保护"}},
    { 1,  "B相过流二段",         &g_TelesignalDB[ADDR_OVERCURRENT_IB_2],             {"复位","保护"},   {"复位","保护"}},	
    { 1,  "C相过流二段",         &g_TelesignalDB[ADDR_OVERCURRENT_IC_2],             {"复位","保护"},   {"复位","保护"}},
    { 1,  "A相过流三段",         &g_TelesignalDB[ADDR_OVERCURRENT_IA_3],             {"复位","保护"},   {"复位","保护"}},
    { 1,  "B相过流三段",         &g_TelesignalDB[ADDR_OVERCURRENT_IB_3],             {"复位","保护"},   {"复位","保护"}},	
    { 1,  "C相过流三段",         &g_TelesignalDB[ADDR_OVERCURRENT_IC_3],             {"复位","保护"},   {"复位","保护"}},
    { 1,  "零序过流一段",        &g_TelesignalDB[ADDR_OVERCURRENT_I0_1],             {"复位","保护"},   {"复位","保护"}},
    { 1,  "零序过流二段",        &g_TelesignalDB[ADDR_OVERCURRENT_I0_2],             {"复位","保护"},   {"复位","保护"}},		
    { 1,  "A相后加速",           &g_TelesignalDB[ADDR_OVERCURRENT_ACC_IA],           {"复位","保护"},   {"复位","保护"}},
    { 1,  "B相后加速",           &g_TelesignalDB[ADDR_OVERCURRENT_ACC_IB],           {"复位","保护"},   {"复位","保护"}},
    { 1,  "C相后加速",           &g_TelesignalDB[ADDR_OVERCURRENT_ACC_IC],           {"复位","保护"},   {"复位","保护"}},
    { 1,  "A相反时限",           &g_TelesignalDB[ADDR_OVERCURRENT_INVERSE_IA],       {"复位","保护"},   {"复位","保护"}},  
    { 1,  "B相反时限",           &g_TelesignalDB[ADDR_OVERCURRENT_INVERSE_IB],       {"复位","保护"},   {"复位","保护"}},
    { 1,  "C相反时限",           &g_TelesignalDB[ADDR_OVERCURRENT_INVERSE_IC],       {"复位","保护"},   {"复位","保护"}},	
    { 1,  "一次重合闸",          &g_TelesignalDB[ADDR_RECLOSE_PROTECTION_1],         {"复位","保护"},   {"复位","保护"}},
    { 1,  "二次重合闸",          &g_TelesignalDB[ADDR_RECLOSE_PROTECTION_2],         {"复位","保护"},   {"复位","保护"}},
    { 1,  "三次重合闸",          &g_TelesignalDB[ADDR_RECLOSE_PROTECTION_3],         {"复位","保护"},   {"复位","保护"}},
    { 1,  "四次重合闸",          &g_TelesignalDB[ADDR_RECLOSE_PROTECTION_4],         {"复位","保护"},   {"复位","保护"}},
    { 1,  "重合闭锁",            &g_TelesignalDB[ADDR_RECLOSE_CLOCK_PROTECTION],     {"复位","闭锁"},   {"复位","闭锁"}},	
    { 1,  "零序一次重合",        &g_TelesignalDB[ADDR_ZERO_RECLOSE_PROTECTION_1],    {"复位","保护"},   {"复位","保护"}},
    { 1,  "零序二次重合",        &g_TelesignalDB[ADDR_ZERO_RECLOSE_PROTECTION_2],    {"复位","保护"},   {"复位","保护"}},			
    { 1,  "二次重合闭锁",        &g_TelesignalDB[ADDR_CLOCK_SECONDARY_CLOSE],        {"复位","闭锁"},   {"复位","闭锁"}},
    { 1,  "失电分闸",            &g_TelesignalDB[ADDR_LOSS_TRIP],                    {"复位","跳闸"},   {"复位","跳闸"}},
    { 1,  "得电合闸",            &g_TelesignalDB[ADDR_GET_CLOSSING_EVENT],           {"复位","合闸"},   {"复位","合闸"}},
    { 1,  "合闸于故障",          &g_TelesignalDB[ADDR_CLOSING_FAULT],                {"无","故障"},     {"无","故障"}},
    { 1,  "保护闭锁",            &g_TelesignalDB[ADDR_PROTECT_CLOCK],                {"复位","闭锁"},   {"复位","闭锁"}},	
    { 1,  "双压禁止合闸",        &g_TelesignalDB[ADDR_DOUBLE_PROHIBIT_CLOSSING],     {"复位","保护"},   {"复位","保护"}},
    { 1,  "单侧失压合闸",        &g_TelesignalDB[ADDR_SINGLE_LOSS_CLOSING_EVENT],    {"复位","动作"},   {"复位","动作"}},
    { 1,  "残压闭锁合闸",        &g_TelesignalDB[ADDR_REMAIN_CLOCK_CLOSSING],        {"复位","保护"},   {"复位","保护"}},	
    { 1,  "接地故障跳闸",        &g_TelesignalDB[ADDR_U0_EARTHING_FAULT_TRIP],       {"复位","保护"},   {"复位","保护"}},
    { 1,  "小信号接地",          &g_TelesignalDB[ADDR_SMALL_SIGNAL_GROUND_LINE_TRIP],{"复位","跳闸"},   {"复位","跳闸"}},
    { 1,  "遮断电流",            &g_TelesignalDB[ADDR_BREAKINGCURRENT],              {"复位","保护"},   {"复位","保护"}},	
    { 1,  "过负荷",              &g_TelesignalDB[ADDR_OVERLOAD_EVENT],               {"复位","告警"},   {"复位","告警"}},
    { 1,  "重过载",              &g_TelesignalDB[ADDR_HAVEY_OVERLOAD_EVENT],         {"复位","告警"},   {"复位","告警"}},
    { 1,  "过压保护",            &g_TelesignalDB[ADDR_OVER_VOLTAGE_PROTECTION],      {"复位","保护"},   {"复位","保护"}},		
    { 1,  "过频保护",            &g_TelesignalDB[ADDR_OVER_FREQUEBNCY_PROTECTION],   {"复位","保护"},   {"复位","保护"}},
    { 1,  "低压保护",            &g_TelesignalDB[ADDR_DOWN_VOLTAGE_PROTECTION],      {"复位","保护"},   {"复位","保护"}},
    { 1,  "低频保护",            &g_TelesignalDB[ADDR_DOWN_FREQUEBNCY_PROTECTION],   {"复位","保护"},   {"复位","保护"}},
    { 1,  "Uab越上限",           &g_TelesignalDB[ADDR_OVERLIMIT_Uab_UP],             {"复位","越上限"}, {"复位","越上限"}},
    { 1,  "Uab越下限",           &g_TelesignalDB[ADDR_OVERLIMIT_Uab_DOWN],           {"复位","越下限"}, {"复位","越下限"}},	
    { 1,  "UBC越上限",           &g_TelesignalDB[ADDR_OVERLIMIT_UBC_UP],             {"复位","越上限"}, {"复位","越上限"}},
    { 1,  "UBC越下限",           &g_TelesignalDB[ADDR_OVERLIMIT_UBC_DOWN],           {"复位","越下限"}, {"复位","越下限"}},	
    { 1,  "Uca越上限",           &g_TelesignalDB[ADDR_OVERLIMIT_Uca_UP],             {"复位","越上限"}, {"复位","越上限"}},	
    { 1,  "Uca越下限",           &g_TelesignalDB[ADDR_OVERLIMIT_Uca_DOWN],           {"复位","越下限"}, {"复位","越下限"}},	
    { 1,  "U0越上限",            &g_TelesignalDB[ADDR_OVERLIMIT_U0_UP],              {"复位","越上限"}, {"复位","越上限"}},	
    { 1,  "U0越下限",            &g_TelesignalDB[ADDR_OVERLIMIT_U0_DOWN],            {"复位","越下限"}, {"复位","越下限"}},	
    { 1,  "Ia越上限",            &g_TelesignalDB[ADDR_OVERLIMIT_IA_UP],              {"复位","越上限"}, {"复位","越上限"}},
    { 1,  "Ia越下限",            &g_TelesignalDB[ADDR_OVERLIMIT_IA_DOWN],            {"复位","越下限"}, {"复位","越下限"}},	
    { 1,  "Ib越上限",            &g_TelesignalDB[ADDR_OVERLIMIT_IB_UP],              {"复位","越上限"}, {"复位","越上限"}},
    { 1,  "Ib越下限",            &g_TelesignalDB[ADDR_OVERLIMIT_IB_DOWN],            {"复位","越下限"}, {"复位","越下限"}},	
    { 1,  "Ic越上限",            &g_TelesignalDB[ADDR_OVERLIMIT_IC_UP],              {"复位","越上限"}, {"复位","越上限"}},	
    { 1,  "Ic越下限",            &g_TelesignalDB[ADDR_OVERLIMIT_IC_DOWN],            {"复位","越下限"}, {"复位","越下限"}},	
    { 1,  "I0越上限",            &g_TelesignalDB[ADDR_OVERLIMIT_I0_UP],              {"复位","越上限"}, {"复位","越上限"}},	
    { 1,  "I0越下限",            &g_TelesignalDB[ADDR_OVERLIMIT_I0_DOWN],            {"复位","越下限"}, {"复位","越下限"}},		
    { 1,  "DC_U越上限",          &g_TelesignalDB[ADDR_OVERLIMIT_DC_U_UP],            {"复位","越上限"}, {"复位","越上限"}},	
    { 1,  "DC_U越下限",          &g_TelesignalDB[ADDR_OVERLIMIT_DC_U_DOWN],          {"复位","越下限"}, {"复位","越下限"}},	
    { 1,  "DC_I越上限",          &g_TelesignalDB[ADDR_OVERLIMIT_DC_I_UP],            {"复位","越上限"}, {"复位","越上限"}},	
    { 1,  "DC_I越下限",          &g_TelesignalDB[ADDR_OVERLIMIT_DC_I_DOWN],          {"复位","越下限"}, {"复位","越下限"}},		
    { 1,  "装置掉电",            &g_TelesignalDB[ADDR_DEVICE_POWER_DOWN],            {"复位","掉电"},    {"复位","掉电"}},
};
	
/* 遥测 */
struct tagTelemetryCfg TelemetryCfg[] = 
{
//   使能 菜单编号     名称                     值                            单位                 校准系数                             零漂                             死区	
    { 1,  SECONDRY,  "频率(f)",          &g_TelemetryDB[ADDR_F],               "Hz",       &g_CalibrateFactor[CALIFACTOR_F],      &g_Parameter[ZERODRIFT_F],      &g_Parameter[DEADZONE_F]},
    { 1,  SECONDRY,  "A相电流(Ia)",      &g_TelemetryDB[ADDR_IA],              "A",        &g_CalibrateFactor[CALIFACTOR_Ia],     &g_Parameter[ZERODRIFT_Ia],     &g_Parameter[DEADZONE_Ia]},
    { 1,  SECONDRY,  "A相电流(Ib)",      &g_TelemetryDB[ADDR_IB],              "A",        &g_CalibrateFactor[CALIFACTOR_Ib],     &g_Parameter[ZERODRIFT_Ib],     &g_Parameter[DEADZONE_Ib]},
    { 1,  SECONDRY,  "A相电流(Ic)",      &g_TelemetryDB[ADDR_IC],              "A",        &g_CalibrateFactor[CALIFACTOR_Ic],     &g_Parameter[ZERODRIFT_Ic],     &g_Parameter[DEADZONE_Ic]},	
    { 1,  SECONDRY,  "零序电流(I0)",     &g_TelemetryDB[ADDR_I0],              "A",        &g_CalibrateFactor[CALIFACTOR_I0],     &g_Parameter[ZERODRIFT_I0],     &g_Parameter[DEADZONE_I0]},
    { 1,  SECONDRY,  "线电压(Uab)",      &g_TelemetryDB[ADDR_Uab],             "V",        &g_CalibrateFactor[CALIFACTOR_Uab],    &g_Parameter[ZERODRIFT_Uab],    &g_Parameter[DEADZONE_Uab]},
    { 1,  SECONDRY,  "线电压(Ubc)",      &g_TelemetryDB[ADDR_Ubc],             "V",        &g_CalibrateFactor[CALIFACTOR_Ubc],    &g_Parameter[ZERODRIFT_Ubc],    &g_Parameter[DEADZONE_Ubc]},
    { 1,  SECONDRY,  "线电压(Uca)",      &g_TelemetryDB[ADDR_Uca],             "V",        &g_CalibrateFactor[CALIFACTOR_Uca],    &g_Parameter[ZERODRIFT_Uca],    &g_Parameter[DEADZONE_Uca]},
    { 1,  SECONDRY,  "零序电压(U0)",     &g_TelemetryDB[ADDR_U0],              "V",        &g_CalibrateFactor[CALIFACTOR_U0],     &g_Parameter[ZERODRIFT_U0],     &g_Parameter[DEADZONE_U0]},
    { 1,  SECONDRY,  "线电压(UAB)",      &g_TelemetryDB[ADDR_UAB],             "V",        &g_CalibrateFactor[CALIFACTOR_UAB],    &g_Parameter[ZERODRIFT_UAB],    &g_Parameter[DEADZONE_UAB]},
    { 1,  SECONDRY,  "线电压(UBC)",      &g_TelemetryDB[ADDR_UBC],             "V",        &g_CalibrateFactor[CALIFACTOR_UBC],    &g_Parameter[ZERODRIFT_UBC],    &g_Parameter[DEADZONE_UBC]},
    { 1,  SECONDRY,  "有功功率(P)",      &g_TelemetryDB[ADDR_P],               "kW",       &g_CalibrateFactor[CALIFACTOR_P],      &g_Parameter[ZERODRIFT_P],      &g_Parameter[DEADZONE_P]},
    { 1,  SECONDRY,  "无功功率(Q)",      &g_TelemetryDB[ADDR_Q],               "kVar",     &g_CalibrateFactor[CALIFACTOR_Q],      &g_Parameter[ZERODRIFT_Q],      &g_Parameter[DEADZONE_Q]},
    { 1,  SECONDRY,  "视在功率(S)",      &g_TelemetryDB[ADDR_S],               "kVA",      &g_CalibrateFactor[CALIFACTOR_S],      &g_Parameter[ZERODRIFT_S],      &g_Parameter[DEADZONE_S]},
    { 1,  SECONDRY,  "功率因数(pf)",     &g_TelemetryDB[ADDR_PF],               "-",       &g_CalibrateFactor[CALIFACTOR_PF],     &g_Parameter[ZERODRIFT_PF],     &g_Parameter[DEADZONE_PF]},
    { 1,  SECONDRY,  "直流电压1",        &g_TelemetryDB[ADDR_DC1],              "V",       &g_CalibrateFactor[CALIFACTOR_DC1],    &g_Parameter[ZERODRIFT_DC1],    &g_Parameter[DEADZONE_DC1]},
    { 1,  SECONDRY,  "直流电压2",        &g_TelemetryDB[ADDR_DC2],              "V",       &g_CalibrateFactor[CALIFACTOR_DC2],    &g_Parameter[ZERODRIFT_DC2],    &g_Parameter[DEADZONE_DC2]},
    { 1,  SECONDRY,  "温度(T)",          &g_TelemetryDB[ADDR_T],                "°C",      &g_CalibrateFactor[CALIFACTOR_T],      &g_Parameter[ZERODRIFT_T],      &g_Parameter[DEADZONE_T]},

	{ 1,  SECONDRY,  "∠Ua_Ia",          &g_TelemetryDB[ADDR_AIPHY_Ua_Ia],      "°",       &g_CalibrateFactor[CALIFACTOR_ALPHA_UaIa],     NULL,                            NULL},
    { 1,  SECONDRY,  "∠Ub_Ib",          &g_TelemetryDB[ADDR_AIPHY_Ub_Ib],      "°",       &g_CalibrateFactor[CALIFACTOR_ALPHA_UbIb],     NULL,                            NULL},
    { 1,  SECONDRY,  "∠UC_Ic",          &g_TelemetryDB[ADDR_AIPHY_UC_Ic],      "°",       &g_CalibrateFactor[CALIFACTOR_ALPHA_UCIc],     NULL,                            NULL},	
    { 1,  SECONDRY,  "∠U0_I0",          &g_TelemetryDB[ADDR_AIPHY_U0_I0],      "°",       &g_CalibrateFactor[CALIFACTOR_ALPHA_U0I0],     NULL,                            NULL},
    { 1,  SECONDRY,  "∠Uab_UBC",        &g_TelemetryDB[ADDR_ALPHY_Uab_UBC],    "°",       &g_CalibrateFactor[CALIFACTOR_ALPHA_UaUb],     NULL,                            NULL},	
	
    { 1,  ONCE,      "一次Ia",           &g_TelemetryDB[ADDR_Ia_ONCE],          "A",       NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次Ib",           &g_TelemetryDB[ADDR_Ib_ONCE],          "A",       NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次Ic",           &g_TelemetryDB[ADDR_Ic_ONCE],          "A",       NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次I0",           &g_TelemetryDB[ADDR_I0_ONCE],          "A",       NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次Uab",          &g_TelemetryDB[ADDR_Uab_ONCE],         "kV",      NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次Ubc",          &g_TelemetryDB[ADDR_Ubc_ONCE],         "kV",      NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次Uca",          &g_TelemetryDB[ADDR_Uca_ONCE],         "kV",      NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次U0",           &g_TelemetryDB[ADDR_U0_ONCE],          "kV",      NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次UAB",          &g_TelemetryDB[ADDR_UAB_ONCE],         "kV",      NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次UBC",          &g_TelemetryDB[ADDR_UBC_ONCE],         "kV",      NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次P",            &g_TelemetryDB[ADDR_P_ONCE],           "kW",      NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次Q",            &g_TelemetryDB[ADDR_Q_ONCE],           "kVar",    NULL,                                  NULL,                           NULL},
    { 1,  ONCE,      "一次S",            &g_TelemetryDB[ADDR_S_ONCE],           "kVA",     NULL,                                  NULL,                           NULL},		

    { 1,  HARMONIC,  "三次谐波Uab",      &g_TelemetryDB[THIRDHARMONIC_Uab],     "V",       &g_CalibrateFactor[CALIFACTOR_Uab],    &g_Parameter[ZERODRIFT_Uab],    &g_Parameter[DEADZONE_Uab]},	
    { 1,  HARMONIC,  "三次谐波Ubc",      &g_TelemetryDB[THIRDHARMONIC_Ubc],     "V",       &g_CalibrateFactor[CALIFACTOR_Ubc],    &g_Parameter[ZERODRIFT_Ubc],    &g_Parameter[DEADZONE_Ubc]},
    { 1,  HARMONIC,  "三次谐波Uca",      &g_TelemetryDB[THIRDHARMONIC_Uca],     "V",       &g_CalibrateFactor[CALIFACTOR_Uca],    &g_Parameter[ZERODRIFT_Uca],    &g_Parameter[DEADZONE_Uca]},
    { 1,  HARMONIC,  "三次谐波U0",       &g_TelemetryDB[THIRDHARMONIC_U0],      "V",       &g_CalibrateFactor[CALIFACTOR_U0],     &g_Parameter[ZERODRIFT_U0],     &g_Parameter[DEADZONE_U0]},
//    { 1,  HARMONIC,  "三次谐波UAB",      &g_TelemetryDB[THIRDHARMONIC_UAB],    "V",      &g_CalibrateFactor[CALIFACTOR_UAB],    &g_Parameter[ZERODRIFT_UAB],    &g_Parameter[DEADZONE_UAB]},
//    { 1,  HARMONIC,  "三次谐波UBC",      &g_TelemetryDB[THIRDHARMONIC_UBC],    "V",      &g_CalibrateFactor[CALIFACTOR_UBC],    &g_Parameter[ZERODRIFT_UBC],    &g_Parameter[DEADZONE_UBC],
    { 1,  HARMONIC,  "三次谐波Ia",       &g_TelemetryDB[THIRDHARMONIC_Ia],      "A",       &g_CalibrateFactor[CALIFACTOR_Ia],     &g_Parameter[ZERODRIFT_Ia],     &g_Parameter[DEADZONE_Ia]},
    { 1,  HARMONIC,  "三次谐波Ib",       &g_TelemetryDB[THIRDHARMONIC_Ib],      "A",       &g_CalibrateFactor[CALIFACTOR_Ib],     &g_Parameter[ZERODRIFT_Ib],     &g_Parameter[DEADZONE_Ib]},
    { 1,  HARMONIC,  "三次谐波Ic",       &g_TelemetryDB[THIRDHARMONIC_Ic],      "A",       &g_CalibrateFactor[CALIFACTOR_Ic],     &g_Parameter[ZERODRIFT_Ic],     &g_Parameter[DEADZONE_Ic]},
    { 1,  HARMONIC,  "三次谐波I0",       &g_TelemetryDB[THIRDHARMONIC_I0],      "A",       &g_CalibrateFactor[CALIFACTOR_I0],     &g_Parameter[ZERODRIFT_I0],     &g_Parameter[DEADZONE_I0]},	
    { 1,  HARMONIC,  "五次谐波Uab",      &g_TelemetryDB[FIFTHHARMONIC_Uab],     "V",       &g_CalibrateFactor[CALIFACTOR_Uab],    &g_Parameter[ZERODRIFT_Uab],    &g_Parameter[DEADZONE_Uab]},	
    { 1,  HARMONIC,  "五次谐波Ubc",      &g_TelemetryDB[FIFTHHARMONIC_Ubc],     "V",       &g_CalibrateFactor[CALIFACTOR_Ubc],    &g_Parameter[ZERODRIFT_Ubc],    &g_Parameter[DEADZONE_Ubc]},
    { 1,  HARMONIC,  "五次谐波Uca",      &g_TelemetryDB[FIFTHHARMONIC_Uca],     "V",       &g_CalibrateFactor[CALIFACTOR_Uca],    &g_Parameter[ZERODRIFT_Uca],    &g_Parameter[DEADZONE_Uca]},
    { 1,  HARMONIC,  "五次谐波U0",       &g_TelemetryDB[FIFTHHARMONIC_U0],      "V",       &g_CalibrateFactor[CALIFACTOR_U0],     &g_Parameter[ZERODRIFT_U0],     &g_Parameter[DEADZONE_U0]},
//    { 1,  HARMONIC,  "五次谐波UAB",     &g_TelemetryDB[FIFTHHARMONIC_UAB],     "V",      &g_CalibrateFactor[CALIFACTOR_UAB],    &g_Parameter[ZERODRIFT_UAB],    &g_Parameter[DEADZONE_UAB]},
//    { 1,  HARMONIC,  "五次谐波UBC",     &g_TelemetryDB[FIFTHHARMONIC_UBC],     "V",      &g_CalibrateFactor[CALIFACTOR_UBC],    &g_Parameter[ZERODRIFT_UBC],    &g_Parameter[DEADZONE_UBC]},
    { 1,  HARMONIC,  "五次谐波Ia",        &g_TelemetryDB[FIFTHHARMONIC_Ia],     "A",       &g_CalibrateFactor[CALIFACTOR_Ia],     &g_Parameter[ZERODRIFT_Ia],     &g_Parameter[DEADZONE_Ia]},
    { 1,  HARMONIC,  "五次谐波Ib",        &g_TelemetryDB[FIFTHHARMONIC_Ib],     "A",       &g_CalibrateFactor[CALIFACTOR_Ib],     &g_Parameter[ZERODRIFT_Ib],     &g_Parameter[DEADZONE_Ib]},
    { 1,  HARMONIC,  "五次谐波Ic",        &g_TelemetryDB[FIFTHHARMONIC_Ic],     "A",       &g_CalibrateFactor[CALIFACTOR_Ic],     &g_Parameter[ZERODRIFT_Ic],     &g_Parameter[DEADZONE_Ic]},
    { 1,  HARMONIC,  "五次谐波I0",        &g_TelemetryDB[FIFTHHARMONIC_I0],     "A",       &g_CalibrateFactor[CALIFACTOR_I0],     &g_Parameter[ZERODRIFT_I0],     &g_Parameter[DEADZONE_I0]},		
	
};	

/* 校准系数 */
struct tagCalibrateFactor CalibrateFactorCfg[] = 
{
//   使能          名称                  校准值	                 遥测                             系数值                            系数上限值       系数下限值      系数缺省值
    { 1,    "频率(f)校准系数",           50.00f,   &g_TelemetryDB[ADDR_F],                &g_CalibrateFactor[CALIFACTOR_F],          1.2f,            0.8f,           1.0f},
    { 1,    "A相电流(Ia)校准系数",       5.00f,    &g_TelemetryDB[ADDR_IA],               &g_CalibrateFactor[CALIFACTOR_Ia],         0.005f,         0.0035f,         0.0043f},
    { 1,    "B相电流(Ib)校准系数",       5.00f,    &g_TelemetryDB[ADDR_IB],               &g_CalibrateFactor[CALIFACTOR_Ib],         0.005f,         0.0035f,         0.0043f},
    { 1,    "C相电流(Ic)校准系数",       5.00f,    &g_TelemetryDB[ADDR_IC],               &g_CalibrateFactor[CALIFACTOR_Ic],         0.005f,         0.0035f,         0.0043f},
  #ifdef SYNTHESIS_I0_ENABLE
    { 1,    "零序电流(I0)校准系数",      1.00f,    &g_TelemetryDB[ADDR_I0],               &g_CalibrateFactor[CALIFACTOR_I0],         0.005f,         0.0035f,         0.0043f},
  #else		
    { 1,    "零序电流(I0)校准系数",      1.00f,    &g_TelemetryDB[ADDR_I0],               &g_CalibrateFactor[CALIFACTOR_I0],         0.001f,         0.0004f,         0.000866f}, 
  #endif		
    { 1,    "线电压(Uab)校准系数",       100.00f,  &g_TelemetryDB[ADDR_Uab],              &g_CalibrateFactor[CALIFACTOR_Uab],        0.02f,          0.0065f,         0.0095f},
    { 1,    "线电压(Ubc)校准系数",       100.00f,  &g_TelemetryDB[ADDR_Ubc],              &g_CalibrateFactor[CALIFACTOR_Ubc],        0.02f,          0.0065f,         0.0095f},
    { 1,    "线电压(Uca)校准系数",       100.00f,  &g_TelemetryDB[ADDR_Uca],              &g_CalibrateFactor[CALIFACTOR_Uca],        0.02f,          0.0065f,         0.0095f},
    { 1,    "线电压(U0)校准系数",        50.00f,   &g_TelemetryDB[ADDR_U0],               &g_CalibrateFactor[CALIFACTOR_U0],         0.02f,          0.0065f,         0.0095f},
    { 1,    "线电压(UAB)校准系数",       100.00f,  &g_TelemetryDB[ADDR_UAB],              &g_CalibrateFactor[CALIFACTOR_UAB],        0.02f,          0.0065f,         0.0095f},
    { 1,    "线电压(UBC)校准系数",       100.00f,  &g_TelemetryDB[ADDR_UBC],              &g_CalibrateFactor[CALIFACTOR_UBC],        0.02f,          0.0065f,         0.0095f},

    { 1,    "直流电压1校准系数",         24,       &g_TelemetryDB[ADDR_DC1],              &g_CalibrateFactor[CALIFACTOR_DC1],        0.5f,           0.001f,          0.01f},
    { 1,    "直流电压2校准系数",         24,       &g_TelemetryDB[ADDR_DC2],              &g_CalibrateFactor[CALIFACTOR_DC2],        0.5f,           0.001f,          0.01f},
    { 1,    "温度校准系数",              0,        &g_TelemetryDB[ADDR_T],                &g_CalibrateFactor[CALIFACTOR_T],          2.0f,           0.0001f,         1.0f},
	
    { 1,    "UA_IA夹角校准系数",         0,        &g_TelemetryDB[ADDR_AIPHY_Ua_Ia],      &g_CalibrateFactor[CALIFACTOR_ALPHA_UaIa], 0.5f,           0.29f,           0.01f},
    { 1,    "UB_IB夹角校准系数",         0,        &g_TelemetryDB[ADDR_AIPHY_Ub_Ib],      &g_CalibrateFactor[CALIFACTOR_ALPHA_UbIb], 0.5f,           0.29f,           0.01f},
    { 1,    "UC_IC夹角校准系数",         0,        &g_TelemetryDB[ADDR_AIPHY_UC_Ic],      &g_CalibrateFactor[CALIFACTOR_ALPHA_UCIc], 0.5f,           0.29f,           0.01f},
    { 1,    "U0_I0夹角校准系数",         0,        &g_TelemetryDB[ADDR_AIPHY_U0_I0],      &g_CalibrateFactor[CALIFACTOR_ALPHA_U0I0], 0.5f,           0.29f,           0.01f},
    { 1,    "Uab_UBC夹角校准系数",       0,        &g_TelemetryDB[ADDR_ALPHY_Uab_UBC],    &g_CalibrateFactor[CALIFACTOR_ALPHA_UaUb], 0.5f,           0.29f,           0.01f},		
};
	
/* 定值0区 */
struct tagValueParaCfg ParameterCfg[] = 
{
//   使能  菜单编号          名称                             值                         单位      上限        下限   缺省值    数据类型     显示内容           备注
    { 1,  ME_BASIC_SET,   "操作机构",        &g_Parameter[OPERATING_MECHANISM],          "-",       1,           0,     0,         2,     {"弹簧", "永磁"    },   " "   },    
    { 1,  ME_BASIC_SET,   "开关类型",        &g_Parameter[SWITCH_TYPE],                  "-",       1,           0,     0,         2,     {"断路器", "负荷开关"},   " "   }, 
    { 1,  ME_BASIC_SET,   "断路器模式",      &g_Parameter[BREAK_WORK_MODE],              "-",       4,           0,     1,         5,     {"无","常规保护","电压时间型","电压电流型","电流计数型"},   " "   },	
    { 1,  ME_BASIC_SET,   "负荷开关模式",    &g_Parameter[LOAD_WORK_MODE],               "-",       4,           0,     0,         5,     {"无","常规保护","电压时间型","电压电流型","分界"},   " "   }, 
    { 1,  ME_BASIC_SET,   "联络开关识别",    &g_Parameter[CONNECT_SWITCH_RECOGNIZE],     "-",       1,           0,     0,         2,     {"手动", "自动"    },   " "   },	
    { 1,  ME_BASIC_SET,   "永磁输出翻转",    &g_Parameter[OUTPUT_OVERTURN],              "-",       1,           0,     0,         2,     {"不翻转", "翻转"  },   " "   }, 
    { 1,  ME_BASIC_SET,   "合闸欠压定值",    &g_Parameter[CAP_UNDERVOLTAGE_CLOSING],     "V",     250.00f,     0.00f,   176,       0,     {"-",  "-"         },   " "   },	
    { 1,  ME_BASIC_SET,   "分闸欠压定值",    &g_Parameter[CAP_UNDERVOLTAGE_OPENING],     "V",     250.00f,     0.00f,   176,       0,     {"-",  "-"         },   " "   }, 
    { 1,  ME_BASIC_SET,   "电容欠压系数",    &g_Parameter[CAP_UNDERVOLTAGE_FACTOR],      "-",      2.00f,      1.00f,   1.2f,      0,     {"-",  "-"         },   " "   },	    
    { 1,  ME_BASIC_SET,   "一次变比_U",      &g_Parameter[RATIO_U_ONE_TURN],             "V",    100000.00f,   0.00f,   10000.00f, 0,     {"-",  "-"         },   " "    }, 
    { 1,  ME_BASIC_SET,   "二次变比_U",      &g_Parameter[RATIO_U_SECONDARY],            "V",     1000.00f,   0.00f,    220.0f,    0,     {"-",  "-"         },   " "    },	
    { 1,  ME_BASIC_SET,   "一次变比_U0",     &g_Parameter[RATIO_U0_ONE_TURN],            "V",     10000.00f,   0.00f,   1,         0,     {"-",  "-"         },   " "    }, 
    { 1,  ME_BASIC_SET,   "二次变比_U0",     &g_Parameter[RATIO_U0_SECONDARY],           "V",     1000.00f,   0.00f,    1,         0,     {"-",  "-"         },   " "    },
    { 1,  ME_BASIC_SET,   "一次变比_I",      &g_Parameter[RATIO_I_ONE_TURN],             "A",    100000.00f,   0.00f,   600,       0,     {"-",  "-"         },   " "    }, 
    { 1,  ME_BASIC_SET,   "二次变比_I",      &g_Parameter[RATIO_I_SECONDARY],            "A",     1000.00f,   0.00f,    5,         0,     {"-",  "-"         },   " "    },	
    { 1,  ME_BASIC_SET,   "一次变比_I0",     &g_Parameter[RATIO_I0_ONE_TURN],            "A",     10000.00f,   0.00f,   20,        0,     {"-",  "-"         },   " "    }, 
    { 1,  ME_BASIC_SET,   "二次变比_I0",     &g_Parameter[RATIO_I0_SECONDARY],           "A",     10000.00f,   0.00f,   1,         0,     {"-",  "-"         },   " "    },	
    { 1,  ME_BASIC_SET,   "开入防抖时间",    &g_Parameter[DI_SHAKING_TIME],              "ms",     99999,        0,     20.0f,     0,     {"-",  "-"         },   " "    },	
    { 1,  ME_BASIC_SET,   "合闸脉宽时间",    &g_Parameter[CLOSING_PULSE_TIME],           "ms",     99999,        0,     60,        0,     {"-",  "-"         },   " "    },
    { 1,  ME_BASIC_SET,   "分闸脉宽时间",    &g_Parameter[OPENING_PULSE_TIME],           "ms",     99999,        0,     60,        0,     {"-",  "-"         },   " "    },	
    { 1,  ME_BASIC_SET,   "反校时间",        &g_Parameter[REVERSE_TIME],                 "ms",     99999,        0,     10000.0,   0,     {"-",  "-"         },   " "    },	
 
    { 1,  ME_ZERODRIFT,   "频率零漂",        &g_Parameter[ZERODRIFT_F],                 "Hz",     99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "A相电流零漂",     &g_Parameter[ZERODRIFT_Ia],                "A",      99.99f,     0.00f,   0.005f,      0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "B相电流零漂",     &g_Parameter[ZERODRIFT_Ib],                "A",      99.99f,     0.00f,   0.005f,      0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "C相电流零漂",     &g_Parameter[ZERODRIFT_Ic],                "A",      99.99f,     0.00f,   0.005f,      0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "零序电流零漂",    &g_Parameter[ZERODRIFT_I0],                "A",      99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },
    { 1,  ME_ZERODRIFT,   "Uab零漂",         &g_Parameter[ZERODRIFT_Uab],               "V",      99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "Ubc零漂",         &g_Parameter[ZERODRIFT_Ubc],               "V",      99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },		
    { 1,  ME_ZERODRIFT,   "Uac零漂",         &g_Parameter[ZERODRIFT_Uca],               "V",      99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "U0零漂",          &g_Parameter[ZERODRIFT_U0],                "V",      99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },
    { 1,  ME_ZERODRIFT,   "UAB零漂",         &g_Parameter[ZERODRIFT_UAB],               "V",      99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "UBC零漂",         &g_Parameter[ZERODRIFT_UBC],               "V",      99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "有功功率零漂",    &g_Parameter[ZERODRIFT_P],                 "kW",     99.99f,     0.00f,   0.0001f,     0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "无功功率零漂",    &g_Parameter[ZERODRIFT_Q],                 "kVar",   99.99f,     0.00f,   0.0001f,     0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "视在功率零漂",    &g_Parameter[ZERODRIFT_S],                 "kVA",    99.99f,     0.00f,   0.0001f,     0,     {"-",  "-"         },   " "    },		
    { 1,  ME_ZERODRIFT,   "功率因数零漂",    &g_Parameter[ZERODRIFT_PF],                "-",      99.99f,     0.00f,   0.001f,      0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "直流1零漂",       &g_Parameter[ZERODRIFT_DC1],               "V",      99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "直流2零漂",       &g_Parameter[ZERODRIFT_DC2],               "V",      99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },	
    { 1,  ME_ZERODRIFT,   "温度零漂",        &g_Parameter[ZERODRIFT_T],                 "°C",     99.99f,     0.00f,   0.1f,        0,     {"-",  "-"         },   " "    },	
	
    { 1,  ME_DEADEZONE,   "频率死区",        &g_Parameter[DEADZONE_F],                   "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "A相电流死区",     &g_Parameter[DEADZONE_Ia],                  "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "B相电流死区",     &g_Parameter[DEADZONE_Ib],                  "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "C相电流死区",     &g_Parameter[DEADZONE_Ic],                  "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "零序电流死区",    &g_Parameter[DEADZONE_I0],                  "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },
    { 1,  ME_DEADEZONE,   "Uab死区",         &g_Parameter[DEADZONE_Uab],                 "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "Ubc死区",         &g_Parameter[DEADZONE_Ubc],                 "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },		
    { 1,  ME_DEADEZONE,   "Uac死区",         &g_Parameter[DEADZONE_Uca],                 "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "U0死区",          &g_Parameter[DEADZONE_U0],                  "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },
    { 1,  ME_DEADEZONE,   "UAB死区",         &g_Parameter[DEADZONE_UAB],                 "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "UBC死区",         &g_Parameter[DEADZONE_UBC],                 "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "有功功率死区",    &g_Parameter[DEADZONE_P],                   "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "无功功率死区",    &g_Parameter[DEADZONE_Q],                   "%",      99.99f,     0.01f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "视在功率死区",    &g_Parameter[DEADZONE_S],                   "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },		
    { 1,  ME_DEADEZONE,   "功率因数死区",    &g_Parameter[DEADZONE_PF],                  "%",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "直流1死区",       &g_Parameter[DEADZONE_DC1],                 "%",      99.99f,     0.00f,   99.99f,     0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "直流2死区",       &g_Parameter[DEADZONE_DC2],                 "%",      99.99f,     0.00f,   99.99f,     0,     {"-",  "-"         },   " "    },	
    { 1,  ME_DEADEZONE,   "温度死区",        &g_Parameter[DEADZONE_T],                   "%",      99.99f,     0.00f,   99.99f,     0,     {"-",  "-"         },   " "    },		
}; 

/* 定值一区 */
struct tagValueParaCfg FixedValueCfg1[] = 
{
//   使能  菜单编号       名称                            值                           单位       上限        下限   缺省值     数据类型     显示内容           备注
    { 1,  INTERGHASE,   "过流一段投退",    &g_FixedValue1[OVER_CURRENT_SWITCH1],          "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  INTERGHASE,   "过流一段电流",    &g_FixedValue1[OVER_CURRENT_VALUE1],           "A",     100.00f,     0.00f,   10,         0,     {"-",  "-"         },   " "   }, 
    { 1,  INTERGHASE,   "过流一段时间",    &g_FixedValue1[OVER_CURRENT_TIME1],            "S",     100.00f,     0.00f,   0,          0,     {"-",  "-"         },   " "   },	
    { 1,  INTERGHASE,   "过流二段投退",    &g_FixedValue1[OVER_CURRENT_SWITCH2],          "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  INTERGHASE,   "过流二段电流",    &g_FixedValue1[OVER_CURRENT_VALUE2],           "A",     100.00f,     0.00f,   8,          0,     {"-",  "-"         },   " "   }, 
    { 1,  INTERGHASE,   "过流二段时间",    &g_FixedValue1[OVER_CURRENT_TIME2],            "S",     100.00f,     0.00f,   3,          0,     {"-",  "-"         },   " "   },	
    { 1,  INTERGHASE,   "过流三段投退",    &g_FixedValue1[OVER_CURRENT_SWITCH3],          "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  INTERGHASE,   "过流三段电流",    &g_FixedValue1[OVER_CURRENT_VALUE3],           "A",     100.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "   }, 
    { 1,  INTERGHASE,   "过流三段时间",    &g_FixedValue1[OVER_CURRENT_TIME3],            "S",     100.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "   },	
    { 1,  ZERO_SEQUE,   "零序一段投退",    &g_FixedValue1[OVER_CURRENTI0_SWITCH1],        "-",       1,           0,     0,          3,     {"退", "投", "告警"},   " "   },    
    { 1,  ZERO_SEQUE,   "零序一段电流",    &g_FixedValue1[OVER_CURRENTI0_VALUE1],         "A",     100.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "   }, 
    { 1,  ZERO_SEQUE,   "零序一段时间",    &g_FixedValue1[OVER_CURRENTI0_TIME1],          "S",     100.00f,     0.00f,   3,          0,     {"-",  "-"         },   " "   },	    
    { 1,  ZERO_SEQUE,   "零序二段投退",    &g_FixedValue1[OVER_CURRENTI0_SWITCH2],        " ",       1,           0,     3,          3,     {"退", "投", "告警"},   " "    },    
    { 1,  ZERO_SEQUE,   "零序二段电流",    &g_FixedValue1[OVER_CURRENTI0_VALUE2],         "A",     100.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "    }, 
    { 1,  ZERO_SEQUE,   "零序二段时间",    &g_FixedValue1[OVER_CURRENTI0_TIME2],          "S",     100.00f,     0.00f,   0,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "越限告警投退",    &g_FixedValue1[OVERLIMIT_SWITCH],              "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },
    { 1,  LIMITATION,   "越限上限系数",    &g_FixedValue1[UPLIMIT_FACTOR],                "-",     1.00f,       0.00f,   0.8f,       0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "越限下限系数",    &g_FixedValue1[DOWNLIMIT_FACTOR],              "-",     2.00f,       1.00f,   1.2,        0,     {"-",  "-"         },   " "    },
    { 1,  LIMITATION,   "越限延时",        &g_FixedValue1[OVERLIMIT_TIME],                "S",     999.99f,       0,     3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "Uab越限投退",     &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_Uab],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },
    { 1,  LIMITATION,   "UBC越限投退",     &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_UBC],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "Uac越限投退",     &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_Uca],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "电压上限定值",    &g_FixedValue1[UPLIMIT_VOLTAGE_U],             "V",     999.99f,     0.00f,   110,        0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "电压下限定值",    &g_FixedValue1[DOWNLIMIT_VOLTAGE_U],           "V",     999.99f,     0.00f,   20,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "Ia越限投退",      &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_IA],     "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },
    { 1,  LIMITATION,   "Ib越限投退",      &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_IB],     "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "Ic越限投退",      &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_IC],     "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "电流上限定值",    &g_FixedValue1[UPLIMIT_CURRENT_I],             "A",     999.99f,     0.00f,   6,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "电流下限定值",    &g_FixedValue1[DOWNLIMIT_CURRENT_I],           "A",     999.99f,     0.00f,   0.5,        0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "U0越限投退",      &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_U0],     "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "U0上限定值",      &g_FixedValue1[UPLIMIT_VOLTAGE_U0],            "V",     999.99f,     0.00f,   100,        0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "U0下限定值",      &g_FixedValue1[DOWNLIMIT_VOLTAGE_U0],          "V",     999.99f,     0.00f,   20,         0,     {"-",  "-"         },   " "    },
    { 1,  LIMITATION,   "I0越限投退",      &g_FixedValue1[OVERLIMIT_ALARM_SWITCH_I0],     "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "I0上限定值",      &g_FixedValue1[UPLIMIT_VOLTAGE_I0],            "A",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "I0下限定值",      &g_FixedValue1[DOWNLIMIT_VOLTAGE_I0],          "A",     999.99f,     0.00f,   0.2f,       0,     {"-",  "-"         },   " "    },		
    { 1,  LIMITATION,   "U_DC越限投退",    &g_FixedValue1[OVERLIMIT_ALARMSWITCH_DC_U],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "U_DC上限定值",    &g_FixedValue1[UPLIMIT_DC_VOLTAGE_U],          "V",     999.99f,     0.00f,   30,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "U_DC下限定值",    &g_FixedValue1[DOWNLIMIT_DC_VOLTAGE_U],        "V",     999.99f,     0.00f,   18,         0,     {"-",  "-"         },   " "    },
    { 1,  LIMITATION,   "I_DC越限投退",    &g_FixedValue1[OVERLIMIT_ALARMSWITCH_DC_I],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "I_DC上限定值",    &g_FixedValue1[UPLIMIT_DC_CURRENT_I],          "A",     999.99f,     0.00f,   0,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "I_DC下限定值",    &g_FixedValue1[DOWNLIMIT_DC_CURRENT_I],        "A",     999.99f,     0.00f,   0,          0,     {"-",  "-"         },   " "    },	
    { 1,  HEAVY_LOAD,   "重过载投退",      &g_FixedValue1[HEAVY_OVERLOAD_SWITCH],         "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  HEAVY_LOAD,   "重过载定值",      &g_FixedValue1[HEAVY_OVERLOAD_VALUE],          "A",     999.99f,     0.00f,   10,         0,     {"-",  "-"         },   " "    },	
    { 1,  HEAVY_LOAD,   "重过载系数",      &g_FixedValue1[HEAVY_OVERLOAD_FACTOR],         "-",      1.00f,      0.01f,   0.8f,       0,     {"-",  "-"         },   " "    },	
    { 1,  HEAVY_LOAD,   "重过载延时",      &g_FixedValue1[HEAVY_OVERLOAD_TIME],           "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },		
    { 1,  OVERLOAD,     "过负荷投退",      &g_FixedValue1[OVERLOAD_SWITCH],               "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  OVERLOAD,     "过负荷定值",      &g_FixedValue1[OVERLOAD_VALUE],                "A",     999.99f,     0.00f,   8,          0,     {"-",  "-"         },   " "    },	
    { 1,  OVERLOAD,     "过负荷系数",      &g_FixedValue1[OVERLOAD_FACTOR],               "-",      1.00f,      0.01f,   0.8,        0,     {"-",  "-"         },   " "    },	
    { 1,  OVERLOAD,     "过负荷延时",      &g_FixedValue1[OVERLOAD_TIME],                 "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  BATTERY_SET,  "低压告警投退",    &g_FixedValue1[BATTERY_LOWVOLTAGE_ALARM_SWITCH],"-",       1,          0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  BATTERY_SET,  "电池低压定值",    &g_FixedValue1[BATTERY_LOWVOLTAGE_VALUE],      "A",     999.99f,     0.00f,   18,         0,     {"-",  "-"         },   " "    },	
    { 1,  BATTERY_SET,  "电池低压系数",    &g_FixedValue1[BATTERY_LOWVOLTAGE_FACTOR],     "-",      2.00f,      1.01f,   1.2f,       0,     {"-",  "-"         },   " "    },	
    { 1,  BATTERY_SET,  "电池低压延时",    &g_FixedValue1[BATTERY_LOWVOLTAGE_TIME],       "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },		
    { 1,  BATTERY_SET,  "电池活化投退",    &g_FixedValue1[BATTERY_ACTIVE_SWITCH],         "-",        1,          0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  BATTERY_SET,  "电池活化周期",    &g_FixedValue1[BATTERY_ACTIVE_CYCLE],          "天",    99999.99f,   0.00f,   0,          0,     {"-",  "-"         },   " "    },	
    { 1,  BATTERY_SET,  "活化持续时间",    &g_FixedValue1[BATTERY_ACTIVE_TIME],           "h",       23,          0,     0,          0,     {"-",  "-"         },   " "    },	
    { 1,  BATTERY_SET,  "活化故障电压",    &g_FixedValue1[BATTERY_ACTIVE_FAULT_VOLTAGE],  "V",     999.99f,     0.00f,   0,          0,     {"-",  "-"         },   " "    },
    { 1,  BATTERY_SET,  "活化故障延时",    &g_FixedValue1[BATTERY_ACTIVE_FAULT_TIME],     "S",     999.99f,     0.00f,   0,          0,     {"-",  "-"         },   " "    },	
    { 1,  AUTO_RESET,   "自动复归投退",    &g_FixedValue1[AUTOMATIC_RESET_SWITCH],        "-",        1,          0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  AUTO_RESET,   "自动复归延时",    &g_FixedValue1[AUTOMATIC_RESET_TIME],          "S",     99999.99f,   0.00f,   99,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过电压投退",      &g_FixedValue1[OVERVOLTAGE_SWITCH],            "-",       1,           0,     0,          3,     {"退", "投", "告警"},   " "    },	
    { 1,  LIMIT_V_F,    "过电压定值",      &g_FixedValue1[OVERVOLTAGE_VALUE],             "V",     9999.99f,    0.00f,   110,        0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过电压延时",      &g_FixedValue1[OVERVOLTAGE_TIME],              "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过电压系数",      &g_FixedValue1[OVERVOLTAGE_FACTOR],            "-",      1.00f,      0.00f,   0.8f,       0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过频投退",        &g_FixedValue1[OVERFREQUENCY_SWITCH],          "-",       1,           0,     0,          3,     {"退", "投", "告警"},   " "    },	
    { 1,  LIMIT_V_F,    "过频定值",        &g_FixedValue1[OVERFREQUENCY_VALUE],           "Hz",     99.99f,     0.00f,   60,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过频延时",        &g_FixedValue1[OVERFREQUENCY_TIME],            "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过频系数",        &g_FixedValue1[OVERFREQUENCY_FACTOR],          "-",      1.00f,      0.00f,   0.8f,       0,     {"-",  "-"         },   " "    },		
    { 1,  LIMIT_V_F,    "低电压投退",      &g_FixedValue1[DOWNVOLTAGE_SWITCH],            "-",       1,           0,     0,          3,     {"退", "投", "告警"},   " "    },	
    { 1,  LIMIT_V_F,    "低电压定值",      &g_FixedValue1[DOWNVOLTAGE_VALUE],             "V",     99999.99f,   0.00f,   30,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "低电压延时",      &g_FixedValue1[DOWNVOLTAGE_TIME],              "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "低电压系数",      &g_FixedValue1[DOWNVOLTAGE_FACTOR],            "-",      2.00f,      1.00f,   1.2,        0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "低频投退",        &g_FixedValue1[DOWNFREQUENCY_SWITCH],          "-",       1,           0,     0,          3,     {"退", "投", "告警"},   " "    },	
    { 1,  LIMIT_V_F,    "低频定值",        &g_FixedValue1[DOWNFREQUENCY_VALUE],           "Hz",     99.99f,     0.00f,   45,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "低频延时",        &g_FixedValue1[DOWNFREQUENCY_TIME],            "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "低频系数",        &g_FixedValue1[DOWNFREQUENCY_FACTOR],          "-",      2.00f,      1.00f,   1.2f,       0,     {"-",  "-"         },   " "    },		
    { 1,  LOOP_CLOSE,   "合环投退",        &g_FixedValue1[CLOSING_LOOP_SWITCH],           "-",       1,           0,     0,          2,     {"退", "投",       },   " "    },	
    { 1,  LOOP_CLOSE,   "两侧压差",        &g_FixedValue1[VOLTAGE_DIFFERENCE],            "V",      30.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  LOOP_CLOSE,   "相角差",          &g_FixedValue1[PHASEANGLE_DIFFERENCE],         "°",      10.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  FAULT_SWITCH, "控制回路异常",    &g_FixedValue1[CONTROL_LOOP_ABNOMAL_ENABLE],   "-",       1,           0,     0,          2,     {"退", "投",       },   " "    },		
    { 1,  OTHER_PROTEC, "反时限投退",      &g_FixedValue1[INVERSE_SWITCH],                "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  OTHER_PROTEC, "反时限定值",      &g_FixedValue1[INVERSE_CURRENT_VALUE],         "A",      99.99f,     0.00f,   10,         0,     {"-",  "-"         },   " "   }, 
    { 1,  OTHER_PROTEC, "反时限延时",      &g_FixedValue1[INVERSE_TIME],                  "S",      99.99f,     0.00f,   0,          0,     {"-",  "-"         },   " "   },	
    { 1,  OTHER_PROTEC, "后加速投退",      &g_FixedValue1[IACC_SWITCH],                   "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  OTHER_PROTEC, "后加速定值",      &g_FixedValue1[IACC_CURRENT_VALUE],            "A",      99.99f,     0.00f,   6,          0,     {"-",  "-"         },   " "   }, 
    { 1,  OTHER_PROTEC, "后加速延时",      &g_FixedValue1[IACC_TIME],                     "S",      99.99f,     0.00f,   1,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "涌流抑制投退",    &g_FixedValue1[INRUSH_SWITCH],                 "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  OTHER_PROTEC, "涌流抑制延时",    &g_FixedValue1[INRUSH_TIME],                   "S",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "   },	
    { 1,  OTHER_PROTEC, "二次重合闭锁",    &g_FixedValue1[SECONDARY_RECLOSE_LOCK_SWITCH], "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  OTHER_PROTEC, "重合闭锁时间",    &g_FixedValue1[SECONDARY_RECLOSE_LOCK_TIME],   "S",      99.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "相间重合次数",    &g_FixedValue1[RECLOSE_TIMES_I],               "次",      4,           0,     2,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "零序重合次数",    &g_FixedValue1[RECLOSE_TIMES_I0],              "次",      2,           0,     1,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "一次重合时间",    &g_FixedValue1[RECLOSE_TIMER1],                "S",      99.99f,     0.00f,   2,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "二次重合时间",    &g_FixedValue1[RECLOSE_TIMER2],                "S",      99.99f,     0.00f,   10,         0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "三次重合时间",    &g_FixedValue1[RECLOSE_TIMER3],                "S",      99.99f,     0.00f,   15,         0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "四次重合时间",    &g_FixedValue1[RECLOSE_TIMER4],                "S",      99.99f,     0.00f,   20,         0,     {"-",  "-"         },   " "   },	
    { 1,  OTHER_PROTEC, "重合复位时间",    &g_FixedValue1[RE_RESET_TIME],                 "S",      99.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "重合充电时间",    &g_FixedValue1[RE_CHARGE_TIME],                "S",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "   },
    { 1,  LOGICAL_FUN,  "有流定值",        &g_FixedValue1[CURRENT_VALUE],                 "A",      99.99f,     0.00f,   0.2f,       0,     {"-",  "-"         },   " "   },
    { 1,  LOGICAL_FUN,  "有压定值",        &g_FixedValue1[VOLTAGE_VALUE],                 "V",     9999.99f,    0.00f,   80,         0,     {"-",  "-"         },   " "   },	
    { 1,  LOGICAL_FUN,  "Y时限",           &g_FixedValue1[FAULT_CHECK_Y_TIME],            "S",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "   },
    { 1,  LOGICAL_FUN,  "闭锁分闸时间",    &g_FixedValue1[SHORT_LOCKED_OPENING_TIME],     "S",      99.99f,     0.00f,   10,         0,     {"-",  "-"         },   " "   },
    { 1,  LOGICAL_FUN,  "失电分闸投退",    &g_FixedValue1[LOSS_ELECTRICITY_SWITCH],       "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  LOGICAL_FUN,  "失电分闸时间",    &g_FixedValue1[LOSS_OPENING_TIME],             "S",      99.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "   },		
    { 1,  LOGICAL_FUN,  "得电合闸投退",    &g_FixedValue1[GET_VOLTAGE_CLOSSING_SWITCH],   "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  LOGICAL_FUN,  "得电合闸时间",    &g_FixedValue1[GET_VOLTAGE_CLOSSING_X_TIME],   "S",      99.99f,     0.00f,   7,          0,     {"-",  "-"         },   " "   },	
    { 1,  LOGICAL_FUN,  "单侧失压合闸",    &g_FixedValue1[SINGLE_LOSS_VOLTAGE_SWITCH],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  LOGICAL_FUN,  "单侧失压时间",    &g_FixedValue1[SINGLE_LOSS_VOLTAGE_XLTIME],    "S",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "   },	
    { 1,  LOGICAL_FUN,  "双侧有压投退",    &g_FixedValue1[DOUBLE_VOLTAGE_SWITCH],         "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },  
    { 1,  LOGICAL_FUN,  "残压脉冲投退",    &g_FixedValue1[REMAIN_VOLTAGE_SWITCH],         "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  LOGICAL_FUN,  "残压整定电压",    &g_FixedValue1[REMAIN_VOLTAGE_VALUE],          "V",      99.99f,     0.00f,   30,         0,     {"-",  "-"         },   " "   },	
    { 1,  LOGICAL_FUN,  "U0保护投退",      &g_FixedValue1[VOLTAGE_U0_SWITCH],             "-",       1,           0,     0,          2,     {"退", "投",       },   " "    },	
    { 1,  LOGICAL_FUN,  "U0保护电压",      &g_FixedValue1[VOLTAGE_U0_VALUE],              "V",      99.99f,     0.00f,   100,        0,     {"-",  "-"         },   " "    },	
    { 1,  LOGICAL_FUN,  "U0保护延时",      &g_FixedValue1[VOLTAGE_U0_TIME],               "S",      99.99f,     0.00f,   1,          0,     {"-",  "-"         },   " "    },
    { 1,  LOGICAL_FUN,  "非遮断投退",      &g_FixedValue1[BREAKING_CURRENT_SWITCH],       "-",       1,           0,     0,          2,     {"退", "投",       },   " "    },	
    { 1,  LOGICAL_FUN,  "非遮断电流",      &g_FixedValue1[BREAKING_CURRENT_VALUE],        "A",     999.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },		
}; 

/* 定值二区 */
struct tagValueParaCfg FixedValueCfg2[] = 
{
//   使能  菜单编号       名称                            值                           单位       上限        下限   缺省值     数据类型     显示内容           备注
    { 1,  INTERGHASE,   "过流一段投退",    &g_FixedValue2[OVER_CURRENT_SWITCH1],          "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  INTERGHASE,   "过流一段电流",    &g_FixedValue2[OVER_CURRENT_VALUE1],           "A",     100.00f,     0.00f,   10,         0,     {"-",  "-"         },   " "   }, 
    { 1,  INTERGHASE,   "过流一段时间",    &g_FixedValue2[OVER_CURRENT_TIME1],            "S",     100.00f,     0.00f,   0,          0,     {"-",  "-"         },   " "   },	
    { 1,  INTERGHASE,   "过流二段投退",    &g_FixedValue2[OVER_CURRENT_SWITCH2],          "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  INTERGHASE,   "过流二段电流",    &g_FixedValue2[OVER_CURRENT_VALUE2],           "A",     100.00f,     0.00f,   8,          0,     {"-",  "-"         },   " "   }, 
    { 1,  INTERGHASE,   "过流二段时间",    &g_FixedValue2[OVER_CURRENT_TIME2],            "S",     100.00f,     0.00f,   3,          0,     {"-",  "-"         },   " "   },	
    { 1,  INTERGHASE,   "过流三段投退",    &g_FixedValue2[OVER_CURRENT_SWITCH3],          "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  INTERGHASE,   "过流三段电流",    &g_FixedValue2[OVER_CURRENT_VALUE3],           "A",     100.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "   }, 
    { 1,  INTERGHASE,   "过流三段时间",    &g_FixedValue2[OVER_CURRENT_TIME3],            "S",     100.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "   },	
    { 1,  ZERO_SEQUE,   "零序一段投退",    &g_FixedValue2[OVER_CURRENTI0_SWITCH1],        "-",       1,           0,     0,          3,     {"退", "投", "告警"},   " "   },    
    { 1,  ZERO_SEQUE,   "零序一段电流",    &g_FixedValue2[OVER_CURRENTI0_VALUE1],         "A",     100.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "   }, 
    { 1,  ZERO_SEQUE,   "零序一段时间",    &g_FixedValue2[OVER_CURRENTI0_TIME1],          "S",     100.00f,     0.00f,   3,          0,     {"-",  "-"         },   " "   },	    
    { 1,  ZERO_SEQUE,   "零序二段投退",    &g_FixedValue2[OVER_CURRENTI0_SWITCH2],        " ",       1,           0,     3,          3,     {"退", "投", "告警"},   " "    },    
    { 1,  ZERO_SEQUE,   "零序二段电流",    &g_FixedValue2[OVER_CURRENTI0_VALUE2],         "A",     100.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "    }, 
    { 1,  ZERO_SEQUE,   "零序二段时间",    &g_FixedValue2[OVER_CURRENTI0_TIME2],          "S",     100.00f,     0.00f,   0,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "越限告警投退",    &g_FixedValue2[OVERLIMIT_SWITCH],              "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },
    { 1,  LIMITATION,   "越限上限系数",    &g_FixedValue2[UPLIMIT_FACTOR],                "-",     1.00f,       0.00f,   0.8f,       0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "越限下限系数",    &g_FixedValue2[DOWNLIMIT_FACTOR],              "-",     2.00f,       1.00f,   1.2,        0,     {"-",  "-"         },   " "    },
    { 1,  LIMITATION,   "越限延时",        &g_FixedValue2[OVERLIMIT_TIME],                "S",     999.99f,       0,     3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "Uab越限投退",     &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_Uab],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },
    { 1,  LIMITATION,   "UBC越限投退",     &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_UBC],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "Uac越限投退",     &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_Uca],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "电压上限定值",    &g_FixedValue2[UPLIMIT_VOLTAGE_U],             "V",     999.99f,     0.00f,   110,        0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "电压下限定值",    &g_FixedValue2[DOWNLIMIT_VOLTAGE_U],           "V",     999.99f,     0.00f,   20,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "Ia越限投退",      &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_IA],     "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },
    { 1,  LIMITATION,   "Ib越限投退",      &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_IB],     "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "Ic越限投退",      &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_IC],     "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "电流上限定值",    &g_FixedValue2[UPLIMIT_CURRENT_I],             "A",     999.99f,     0.00f,   6,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "电流下限定值",    &g_FixedValue2[DOWNLIMIT_CURRENT_I],           "A",     999.99f,     0.00f,   0.5,        0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "U0越限投退",      &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_U0],     "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "U0上限定值",      &g_FixedValue2[UPLIMIT_VOLTAGE_U0],            "V",     999.99f,     0.00f,   100,        0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "U0下限定值",      &g_FixedValue2[DOWNLIMIT_VOLTAGE_U0],          "V",     999.99f,     0.00f,   20,         0,     {"-",  "-"         },   " "    },
    { 1,  LIMITATION,   "I0越限投退",      &g_FixedValue2[OVERLIMIT_ALARM_SWITCH_I0],     "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "I0上限定值",      &g_FixedValue2[UPLIMIT_VOLTAGE_I0],            "A",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "I0下限定值",      &g_FixedValue2[DOWNLIMIT_VOLTAGE_I0],          "A",     999.99f,     0.00f,   0.2f,       0,     {"-",  "-"         },   " "    },		
    { 1,  LIMITATION,   "U_DC越限投退",    &g_FixedValue2[OVERLIMIT_ALARMSWITCH_DC_U],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "U_DC上限定值",    &g_FixedValue2[UPLIMIT_DC_VOLTAGE_U],          "V",     999.99f,     0.00f,   30,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "U_DC下限定值",    &g_FixedValue2[DOWNLIMIT_DC_VOLTAGE_U],        "V",     999.99f,     0.00f,   18,         0,     {"-",  "-"         },   " "    },
    { 1,  LIMITATION,   "I_DC越限投退",    &g_FixedValue2[OVERLIMIT_ALARMSWITCH_DC_I],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  LIMITATION,   "I_DC上限定值",    &g_FixedValue2[UPLIMIT_DC_CURRENT_I],          "A",     999.99f,     0.00f,   0,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMITATION,   "I_DC下限定值",    &g_FixedValue2[DOWNLIMIT_DC_CURRENT_I],        "A",     999.99f,     0.00f,   0,          0,     {"-",  "-"         },   " "    },	
    { 1,  HEAVY_LOAD,   "重过载投退",      &g_FixedValue2[HEAVY_OVERLOAD_SWITCH],         "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  HEAVY_LOAD,   "重过载定值",      &g_FixedValue2[HEAVY_OVERLOAD_VALUE],          "A",     999.99f,     0.00f,   10,         0,     {"-",  "-"         },   " "    },	
    { 1,  HEAVY_LOAD,   "重过载系数",      &g_FixedValue2[HEAVY_OVERLOAD_FACTOR],         "-",      1.00f,      0.01f,   0.8f,       0,     {"-",  "-"         },   " "    },	
    { 1,  HEAVY_LOAD,   "重过载延时",      &g_FixedValue2[HEAVY_OVERLOAD_TIME],           "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },		
    { 1,  OVERLOAD,     "过负荷投退",      &g_FixedValue2[OVERLOAD_SWITCH],               "-",       1,           0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  OVERLOAD,     "过负荷定值",      &g_FixedValue2[OVERLOAD_VALUE],                "A",     999.99f,     0.00f,   8,          0,     {"-",  "-"         },   " "    },	
    { 1,  OVERLOAD,     "过负荷系数",      &g_FixedValue2[OVERLOAD_FACTOR],               "-",      1.00f,      0.01f,   0.8,        0,     {"-",  "-"         },   " "    },	
    { 1,  OVERLOAD,     "过负荷延时",      &g_FixedValue2[OVERLOAD_TIME],                 "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  BATTERY_SET,  "低压告警投退",    &g_FixedValue2[BATTERY_LOWVOLTAGE_ALARM_SWITCH],"-",       1,          0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  BATTERY_SET,  "电池低压定值",    &g_FixedValue2[BATTERY_LOWVOLTAGE_VALUE],      "A",     999.99f,     0.00f,   18,         0,     {"-",  "-"         },   " "    },	
    { 1,  BATTERY_SET,  "电池低压系数",    &g_FixedValue2[BATTERY_LOWVOLTAGE_FACTOR],     "-",      2.00f,      1.01f,   1.2f,       0,     {"-",  "-"         },   " "    },	
    { 1,  BATTERY_SET,  "电池低压延时",    &g_FixedValue2[BATTERY_LOWVOLTAGE_TIME],       "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },		
    { 1,  BATTERY_SET,  "电池活化投退",    &g_FixedValue2[BATTERY_ACTIVE_SWITCH],         "-",        1,          0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  BATTERY_SET,  "电池活化周期",    &g_FixedValue2[BATTERY_ACTIVE_CYCLE],          "天",    99999.99f,   0.00f,   0,          0,     {"-",  "-"         },   " "    },	
    { 1,  BATTERY_SET,  "活化持续时间",    &g_FixedValue2[BATTERY_ACTIVE_TIME],           "h",       23,          0,     0,          0,     {"-",  "-"         },   " "    },	
    { 1,  BATTERY_SET,  "活化故障电压",    &g_FixedValue2[BATTERY_ACTIVE_FAULT_VOLTAGE],  "V",     999.99f,     0.00f,   0,          0,     {"-",  "-"         },   " "    },
    { 1,  BATTERY_SET,  "活化故障延时",    &g_FixedValue2[BATTERY_ACTIVE_FAULT_TIME],     "S",     999.99f,     0.00f,   0,          0,     {"-",  "-"         },   " "    },	
    { 1,  AUTO_RESET,   "自动复归投退",    &g_FixedValue2[AUTOMATIC_RESET_SWITCH],        "-",        1,          0,     0,          2,     {"退", "投"        },   " "    },	
    { 1,  AUTO_RESET,   "自动复归延时",    &g_FixedValue2[AUTOMATIC_RESET_TIME],          "S",     99999.99f,   0.00f,   99,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过电压投退",      &g_FixedValue2[OVERVOLTAGE_SWITCH],            "-",       1,           0,     0,          3,     {"退", "投", "告警"},   " "    },	
    { 1,  LIMIT_V_F,    "过电压定值",      &g_FixedValue2[OVERVOLTAGE_VALUE],             "V",     9999.99f,    0.00f,   110,        0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过电压延时",      &g_FixedValue2[OVERVOLTAGE_TIME],              "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过电压系数",      &g_FixedValue2[OVERVOLTAGE_FACTOR],            "-",      1.00f,      0.00f,   0.8f,       0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过频投退",        &g_FixedValue2[OVERFREQUENCY_SWITCH],          "-",       1,           0,     0,          3,     {"退", "投", "告警"},   " "    },	
    { 1,  LIMIT_V_F,    "过频定值",        &g_FixedValue2[OVERFREQUENCY_VALUE],           "Hz",     99.99f,     0.00f,   60,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过频延时",        &g_FixedValue2[OVERFREQUENCY_TIME],            "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "过频系数",        &g_FixedValue2[OVERFREQUENCY_FACTOR],          "-",      1.00f,      0.00f,   0.8f,       0,     {"-",  "-"         },   " "    },		
    { 1,  LIMIT_V_F,    "低电压投退",      &g_FixedValue2[DOWNVOLTAGE_SWITCH],            "-",       1,           0,     0,          3,     {"退", "投", "告警"},   " "    },	
    { 1,  LIMIT_V_F,    "低电压定值",      &g_FixedValue2[DOWNVOLTAGE_VALUE],             "V",     99999.99f,   0.00f,   30,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "低电压延时",      &g_FixedValue2[DOWNVOLTAGE_TIME],              "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "低电压系数",      &g_FixedValue2[DOWNVOLTAGE_FACTOR],            "-",      2.00f,      1.00f,   1.2,        0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "低频投退",        &g_FixedValue2[DOWNFREQUENCY_SWITCH],          "-",       1,           0,     0,          3,     {"退", "投", "告警"},   " "    },	
    { 1,  LIMIT_V_F,    "低频定值",        &g_FixedValue2[DOWNFREQUENCY_VALUE],           "Hz",     99.99f,     0.00f,   45,         0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "低频延时",        &g_FixedValue2[DOWNFREQUENCY_TIME],            "S",     999.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "    },	
    { 1,  LIMIT_V_F,    "低频系数",        &g_FixedValue2[DOWNFREQUENCY_FACTOR],          "-",      2.00f,      1.00f,   1.2f,       0,     {"-",  "-"         },   " "    },		
    { 1,  LOOP_CLOSE,   "合环投退",        &g_FixedValue2[CLOSING_LOOP_SWITCH],           "-",       1,           0,     0,          2,     {"退", "投",       },   " "    },	
    { 1,  LOOP_CLOSE,   "两侧压差",        &g_FixedValue2[VOLTAGE_DIFFERENCE],            "V",      30.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  LOOP_CLOSE,   "相角差",          &g_FixedValue2[PHASEANGLE_DIFFERENCE],         "°",      10.00f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
    { 1,  FAULT_SWITCH, "控制回路异常",    &g_FixedValue2[CONTROL_LOOP_ABNOMAL_ENABLE],   "-",       1,           0,     0,          2,     {"退", "投",       },   " "    },		
    { 1,  OTHER_PROTEC, "反时限投退",      &g_FixedValue2[INVERSE_SWITCH],                "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  OTHER_PROTEC, "反时限定值",      &g_FixedValue2[INVERSE_CURRENT_VALUE],         "A",      99.99f,     0.00f,   10,         0,     {"-",  "-"         },   " "   }, 
    { 1,  OTHER_PROTEC, "反时限延时",      &g_FixedValue2[INVERSE_TIME],                  "S",      99.99f,     0.00f,   0,          0,     {"-",  "-"         },   " "   },	
    { 1,  OTHER_PROTEC, "后加速投退",      &g_FixedValue2[IACC_SWITCH],                   "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  OTHER_PROTEC, "后加速定值",      &g_FixedValue2[IACC_CURRENT_VALUE],            "A",      99.99f,     0.00f,   6,          0,     {"-",  "-"         },   " "   }, 
    { 1,  OTHER_PROTEC, "后加速延时",      &g_FixedValue2[IACC_TIME],                     "S",      99.99f,     0.00f,   1,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "涌流抑制投退",    &g_FixedValue2[INRUSH_SWITCH],                 "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  OTHER_PROTEC, "涌流抑制延时",    &g_FixedValue2[INRUSH_TIME],                   "S",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "   },	
    { 1,  OTHER_PROTEC, "二次重合闭锁",    &g_FixedValue2[SECONDARY_RECLOSE_LOCK_SWITCH], "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  OTHER_PROTEC, "重合闭锁时间",    &g_FixedValue2[SECONDARY_RECLOSE_LOCK_TIME],   "S",      99.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "相间重合次数",    &g_FixedValue2[RECLOSE_TIMES_I],               "次",      4,           0,     2,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "零序重合次数",    &g_FixedValue2[RECLOSE_TIMES_I0],              "次",      2,           0,     1,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "一次重合时间",    &g_FixedValue2[RECLOSE_TIMER1],                "S",      99.99f,     0.00f,   2,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "二次重合时间",    &g_FixedValue2[RECLOSE_TIMER2],                "S",      99.99f,     0.00f,   10,         0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "三次重合时间",    &g_FixedValue2[RECLOSE_TIMER3],                "S",      99.99f,     0.00f,   15,         0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "四次重合时间",    &g_FixedValue2[RECLOSE_TIMER4],                "S",      99.99f,     0.00f,   20,         0,     {"-",  "-"         },   " "   },	
    { 1,  OTHER_PROTEC, "重合复位时间",    &g_FixedValue2[RE_RESET_TIME],                 "S",      99.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "   },
    { 1,  OTHER_PROTEC, "重合充电时间",    &g_FixedValue2[RE_CHARGE_TIME],                "S",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "   },
    { 1,  LOGICAL_FUN,  "有流定值",        &g_FixedValue2[CURRENT_VALUE],                 "A",      99.99f,     0.00f,   0.2f,       0,     {"-",  "-"         },   " "   },
    { 1,  LOGICAL_FUN,  "有压定值",        &g_FixedValue2[VOLTAGE_VALUE],                 "V",     9999.99f,    0.00f,   80,         0,     {"-",  "-"         },   " "   },	
    { 1,  LOGICAL_FUN,  "Y时限",           &g_FixedValue2[FAULT_CHECK_Y_TIME],            "S",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "   },
    { 1,  LOGICAL_FUN,  "闭锁分闸时间",    &g_FixedValue2[SHORT_LOCKED_OPENING_TIME],     "S",      99.99f,     0.00f,   10,         0,     {"-",  "-"         },   " "   },
    { 1,  LOGICAL_FUN,  "失电分闸投退",    &g_FixedValue2[LOSS_ELECTRICITY_SWITCH],       "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  LOGICAL_FUN,  "失电分闸时间",    &g_FixedValue2[LOSS_OPENING_TIME],             "S",      99.99f,     0.00f,   3,          0,     {"-",  "-"         },   " "   },		
    { 1,  LOGICAL_FUN,  "得电合闸投退",    &g_FixedValue2[GET_VOLTAGE_CLOSSING_SWITCH],   "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  LOGICAL_FUN,  "得电合闸时间",    &g_FixedValue2[GET_VOLTAGE_CLOSSING_X_TIME],   "S",      99.99f,     0.00f,   7,          0,     {"-",  "-"         },   " "   },	
    { 1,  LOGICAL_FUN,  "单侧失压合闸",    &g_FixedValue2[SINGLE_LOSS_VOLTAGE_SWITCH],    "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  LOGICAL_FUN,  "单侧失压时间",    &g_FixedValue2[SINGLE_LOSS_VOLTAGE_XLTIME],    "S",      99.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "   },	
    { 1,  LOGICAL_FUN,  "双侧有压投退",    &g_FixedValue2[DOUBLE_VOLTAGE_SWITCH],         "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },  
    { 1,  LOGICAL_FUN,  "残压脉冲投退",    &g_FixedValue2[REMAIN_VOLTAGE_SWITCH],         "-",       1,           0,     0,          2,     {"退", "投"        },   " "   },    
    { 1,  LOGICAL_FUN,  "残压整定电压",    &g_FixedValue2[REMAIN_VOLTAGE_VALUE],          "V",      99.99f,     0.00f,   30,         0,     {"-",  "-"         },   " "   },	
    { 1,  LOGICAL_FUN,  "U0保护投退",      &g_FixedValue2[VOLTAGE_U0_SWITCH],             "-",       1,           0,     0,          2,     {"退", "投",       },   " "    },	
    { 1,  LOGICAL_FUN,  "U0保护电压",      &g_FixedValue2[VOLTAGE_U0_VALUE],              "V",      99.99f,     0.00f,   100,        0,     {"-",  "-"         },   " "    },	
    { 1,  LOGICAL_FUN,  "U0保护延时",      &g_FixedValue2[VOLTAGE_U0_TIME],               "S",      99.99f,     0.00f,   1,          0,     {"-",  "-"         },   " "    },
    { 1,  LOGICAL_FUN,  "非遮断投退",      &g_FixedValue2[BREAKING_CURRENT_SWITCH],       "-",       1,           0,     0,          2,     {"退", "投",       },   " "    },	
    { 1,  LOGICAL_FUN,  "非遮断电流",      &g_FixedValue2[BREAKING_CURRENT_VALUE],        "A",     999.99f,     0.00f,   5,          0,     {"-",  "-"         },   " "    },	
};


unsigned int g_FixedValueCfg1_Len = sizeof(FixedValueCfg1) / sizeof(FixedValueCfg1[0]);
unsigned int g_FixedValueCfg2_Len = sizeof(FixedValueCfg2) / sizeof(FixedValueCfg2[0]);
unsigned int g_ParameterCfg_Len = sizeof(ParameterCfg) / sizeof(ParameterCfg[0]);
unsigned int g_CalibrateFactorCfg_Len = sizeof(CalibrateFactorCfg) / sizeof(CalibrateFactorCfg[0]);
unsigned int g_TelemetryCfg_Len = sizeof(TelemetryCfg) / sizeof(TelemetryCfg[0]);
unsigned int g_TelesignalCfg_Len = sizeof(TelesignalCfg) / sizeof(TelesignalCfg[0]);


/* END OF FILE ---------------------------------------------------------------*/


