/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Jun 30 13:42:35 2018. */

#include "log.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ExceptionRecord_fields[6] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, ExceptionRecord, id, id, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, ExceptionRecord, time, id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, ExceptionRecord, functionName, time, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, ExceptionRecord, line, functionName, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, ExceptionRecord, code, line, 0),
    PB_LAST_FIELD
};

const pb_field_t LogRecord_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, LogRecord, exception, exception, &ExceptionRecord_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(LogRecord, exception[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ExceptionRecord_LogRecord)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(LogRecord, exception[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ExceptionRecord_LogRecord)
#endif


/* @@protoc_insertion_point(eof) */
