/*
 * static_model.h
 *
 * automatically generated from test_goose.icd
 */

#ifndef STATIC_MODEL_H_
#define STATIC_MODEL_H_

#include <stdlib.h>
#include "iec61850_model.h"

extern IedModel iedModel;
extern LogicalDevice iedModel_LD0;
extern LogicalNode   iedModel_LD0_LLN0;
extern DataObject    iedModel_LD0_LLN0_Mod;
extern DataAttribute iedModel_LD0_LLN0_Mod_q;
extern DataAttribute iedModel_LD0_LLN0_Mod_t;
extern DataAttribute iedModel_LD0_LLN0_Mod_ctlModel;
extern DataObject    iedModel_LD0_LLN0_Beh;
extern DataAttribute iedModel_LD0_LLN0_Beh_stVal;
extern DataAttribute iedModel_LD0_LLN0_Beh_q;
extern DataAttribute iedModel_LD0_LLN0_Beh_t;
extern DataObject    iedModel_LD0_LLN0_Health;
extern DataAttribute iedModel_LD0_LLN0_Health_stVal;
extern DataAttribute iedModel_LD0_LLN0_Health_q;
extern DataAttribute iedModel_LD0_LLN0_Health_t;
extern DataObject    iedModel_LD0_LLN0_NamPlt;
extern DataAttribute iedModel_LD0_LLN0_NamPlt_vendor;
extern DataAttribute iedModel_LD0_LLN0_NamPlt_swRev;
extern DataAttribute iedModel_LD0_LLN0_NamPlt_d;
extern DataAttribute iedModel_LD0_LLN0_NamPlt_configRev;
extern DataAttribute iedModel_LD0_LLN0_NamPlt_ldNs;
extern LogicalNode   iedModel_LD0_LPHD1;
extern DataObject    iedModel_LD0_LPHD1_PhyNam;
extern DataAttribute iedModel_LD0_LPHD1_PhyNam_vendor;
extern DataObject    iedModel_LD0_LPHD1_PhyHealth;
extern DataAttribute iedModel_LD0_LPHD1_PhyHealth_stVal;
extern DataAttribute iedModel_LD0_LPHD1_PhyHealth_q;
extern DataAttribute iedModel_LD0_LPHD1_PhyHealth_t;
extern DataObject    iedModel_LD0_LPHD1_Proxy;
extern DataAttribute iedModel_LD0_LPHD1_Proxy_stVal;
extern DataAttribute iedModel_LD0_LPHD1_Proxy_q;
extern DataAttribute iedModel_LD0_LPHD1_Proxy_t;
extern LogicalNode   iedModel_LD0_GGIO1;
extern DataObject    iedModel_LD0_GGIO1_Mod;
extern DataAttribute iedModel_LD0_GGIO1_Mod_q;
extern DataAttribute iedModel_LD0_GGIO1_Mod_t;
extern DataAttribute iedModel_LD0_GGIO1_Mod_ctlModel;
extern DataObject    iedModel_LD0_GGIO1_Beh;
extern DataAttribute iedModel_LD0_GGIO1_Beh_stVal;
extern DataAttribute iedModel_LD0_GGIO1_Beh_q;
extern DataAttribute iedModel_LD0_GGIO1_Beh_t;
extern DataObject    iedModel_LD0_GGIO1_Health;
extern DataAttribute iedModel_LD0_GGIO1_Health_stVal;
extern DataAttribute iedModel_LD0_GGIO1_Health_q;
extern DataAttribute iedModel_LD0_GGIO1_Health_t;
extern DataObject    iedModel_LD0_GGIO1_NamPlt;
extern DataAttribute iedModel_LD0_GGIO1_NamPlt_vendor;
extern DataAttribute iedModel_LD0_GGIO1_NamPlt_swRev;
extern DataAttribute iedModel_LD0_GGIO1_NamPlt_d;
extern DataObject    iedModel_LD0_GGIO1_Ind1;
extern DataAttribute iedModel_LD0_GGIO1_Ind1_stVal;
extern DataAttribute iedModel_LD0_GGIO1_Ind1_q;
extern DataAttribute iedModel_LD0_GGIO1_Ind1_t;
extern DataObject    iedModel_LD0_GGIO1_Ind2;
extern DataAttribute iedModel_LD0_GGIO1_Ind2_stVal;
extern DataAttribute iedModel_LD0_GGIO1_Ind2_q;
extern DataAttribute iedModel_LD0_GGIO1_Ind2_t;
extern DataObject    iedModel_LD0_GGIO1_Ind3;
extern DataAttribute iedModel_LD0_GGIO1_Ind3_stVal;
extern DataAttribute iedModel_LD0_GGIO1_Ind3_q;
extern DataAttribute iedModel_LD0_GGIO1_Ind3_t;
extern DataObject    iedModel_LD0_GGIO1_Ind4;
extern DataAttribute iedModel_LD0_GGIO1_Ind4_stVal;
extern DataAttribute iedModel_LD0_GGIO1_Ind4_q;
extern DataAttribute iedModel_LD0_GGIO1_Ind4_t;
extern DataObject    iedModel_LD0_GGIO1_Ind5;
extern DataAttribute iedModel_LD0_GGIO1_Ind5_stVal;
extern DataAttribute iedModel_LD0_GGIO1_Ind5_q;
extern DataAttribute iedModel_LD0_GGIO1_Ind5_t;
extern DataObject    iedModel_LD0_GGIO1_Ind6;
extern DataAttribute iedModel_LD0_GGIO1_Ind6_stVal;
extern DataAttribute iedModel_LD0_GGIO1_Ind6_q;
extern DataAttribute iedModel_LD0_GGIO1_Ind6_t;
extern DataObject    iedModel_LD0_GGIO1_Ind7;
extern DataAttribute iedModel_LD0_GGIO1_Ind7_stVal;
extern DataAttribute iedModel_LD0_GGIO1_Ind7_q;
extern DataAttribute iedModel_LD0_GGIO1_Ind7_t;
extern DataObject    iedModel_LD0_GGIO1_Ind8;
extern DataAttribute iedModel_LD0_GGIO1_Ind8_stVal;
extern DataAttribute iedModel_LD0_GGIO1_Ind8_q;
extern DataAttribute iedModel_LD0_GGIO1_Ind8_t;
extern LogicalDevice iedModel_MEAS;
extern LogicalNode   iedModel_MEAS_LLN0;
extern DataObject    iedModel_MEAS_LLN0_Mod;
extern DataAttribute iedModel_MEAS_LLN0_Mod_q;
extern DataAttribute iedModel_MEAS_LLN0_Mod_t;
extern DataAttribute iedModel_MEAS_LLN0_Mod_ctlModel;
extern DataObject    iedModel_MEAS_LLN0_Beh;
extern DataAttribute iedModel_MEAS_LLN0_Beh_stVal;
extern DataAttribute iedModel_MEAS_LLN0_Beh_q;
extern DataAttribute iedModel_MEAS_LLN0_Beh_t;
extern DataObject    iedModel_MEAS_LLN0_Health;
extern DataAttribute iedModel_MEAS_LLN0_Health_stVal;
extern DataAttribute iedModel_MEAS_LLN0_Health_q;
extern DataAttribute iedModel_MEAS_LLN0_Health_t;
extern DataObject    iedModel_MEAS_LLN0_NamPlt;
extern DataAttribute iedModel_MEAS_LLN0_NamPlt_vendor;
extern DataAttribute iedModel_MEAS_LLN0_NamPlt_swRev;
extern DataAttribute iedModel_MEAS_LLN0_NamPlt_d;
extern DataAttribute iedModel_MEAS_LLN0_NamPlt_configRev;
extern DataAttribute iedModel_MEAS_LLN0_NamPlt_ldNs;
extern LogicalNode   iedModel_MEAS_LPHD1;
extern DataObject    iedModel_MEAS_LPHD1_PhyNam;
extern DataAttribute iedModel_MEAS_LPHD1_PhyNam_vendor;
extern DataObject    iedModel_MEAS_LPHD1_PhyHealth;
extern DataAttribute iedModel_MEAS_LPHD1_PhyHealth_stVal;
extern DataAttribute iedModel_MEAS_LPHD1_PhyHealth_q;
extern DataAttribute iedModel_MEAS_LPHD1_PhyHealth_t;
extern DataObject    iedModel_MEAS_LPHD1_Proxy;
extern DataAttribute iedModel_MEAS_LPHD1_Proxy_stVal;
extern DataAttribute iedModel_MEAS_LPHD1_Proxy_q;
extern DataAttribute iedModel_MEAS_LPHD1_Proxy_t;
extern LogicalNode   iedModel_MEAS_MMXU1;
extern DataObject    iedModel_MEAS_MMXU1_Mod;
extern DataAttribute iedModel_MEAS_MMXU1_Mod_q;
extern DataAttribute iedModel_MEAS_MMXU1_Mod_t;
extern DataAttribute iedModel_MEAS_MMXU1_Mod_ctlModel;
extern DataObject    iedModel_MEAS_MMXU1_Beh;
extern DataAttribute iedModel_MEAS_MMXU1_Beh_stVal;
extern DataAttribute iedModel_MEAS_MMXU1_Beh_q;
extern DataAttribute iedModel_MEAS_MMXU1_Beh_t;
extern DataObject    iedModel_MEAS_MMXU1_Health;
extern DataAttribute iedModel_MEAS_MMXU1_Health_stVal;
extern DataAttribute iedModel_MEAS_MMXU1_Health_q;
extern DataAttribute iedModel_MEAS_MMXU1_Health_t;
extern DataObject    iedModel_MEAS_MMXU1_NamPlt;
extern DataAttribute iedModel_MEAS_MMXU1_NamPlt_vendor;
extern DataAttribute iedModel_MEAS_MMXU1_NamPlt_swRev;
extern DataAttribute iedModel_MEAS_MMXU1_NamPlt_d;
extern DataObject    iedModel_MEAS_MMXU1_Hz;
extern DataAttribute iedModel_MEAS_MMXU1_Hz_mag;
extern DataAttribute iedModel_MEAS_MMXU1_Hz_mag_f;
extern DataAttribute iedModel_MEAS_MMXU1_Hz_q;
extern DataAttribute iedModel_MEAS_MMXU1_Hz_t;
extern DataObject    iedModel_MEAS_MMXU1_PhV;
extern DataObject    iedModel_MEAS_MMXU1_PhV_phsA;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsA_cVal;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsA_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsA_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsA_q;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsA_t;
extern DataObject    iedModel_MEAS_MMXU1_PhV_phsB;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsB_cVal;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsB_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsB_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsB_q;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsB_t;
extern DataObject    iedModel_MEAS_MMXU1_PhV_phsC;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsC_cVal;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsC_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsC_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsC_q;
extern DataAttribute iedModel_MEAS_MMXU1_PhV_phsC_t;
extern DataObject    iedModel_MEAS_MMXU1_A;
extern DataObject    iedModel_MEAS_MMXU1_A_phsA;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsA_cVal;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsA_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsA_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsA_q;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsA_t;
extern DataObject    iedModel_MEAS_MMXU1_A_phsB;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsB_cVal;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsB_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsB_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsB_q;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsB_t;
extern DataObject    iedModel_MEAS_MMXU1_A_phsC;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsC_cVal;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsC_cVal_mag;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsC_cVal_mag_f;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsC_q;
extern DataAttribute iedModel_MEAS_MMXU1_A_phsC_t;



#define IEDMODEL_LD0 (&iedModel_LD0)
#define IEDMODEL_LD0_LLN0 (&iedModel_LD0_LLN0)
#define IEDMODEL_LD0_LLN0_Mod (&iedModel_LD0_LLN0_Mod)
#define IEDMODEL_LD0_LLN0_Mod_q (&iedModel_LD0_LLN0_Mod_q)
#define IEDMODEL_LD0_LLN0_Mod_t (&iedModel_LD0_LLN0_Mod_t)
#define IEDMODEL_LD0_LLN0_Mod_ctlModel (&iedModel_LD0_LLN0_Mod_ctlModel)
#define IEDMODEL_LD0_LLN0_Beh (&iedModel_LD0_LLN0_Beh)
#define IEDMODEL_LD0_LLN0_Beh_stVal (&iedModel_LD0_LLN0_Beh_stVal)
#define IEDMODEL_LD0_LLN0_Beh_q (&iedModel_LD0_LLN0_Beh_q)
#define IEDMODEL_LD0_LLN0_Beh_t (&iedModel_LD0_LLN0_Beh_t)
#define IEDMODEL_LD0_LLN0_Health (&iedModel_LD0_LLN0_Health)
#define IEDMODEL_LD0_LLN0_Health_stVal (&iedModel_LD0_LLN0_Health_stVal)
#define IEDMODEL_LD0_LLN0_Health_q (&iedModel_LD0_LLN0_Health_q)
#define IEDMODEL_LD0_LLN0_Health_t (&iedModel_LD0_LLN0_Health_t)
#define IEDMODEL_LD0_LLN0_NamPlt (&iedModel_LD0_LLN0_NamPlt)
#define IEDMODEL_LD0_LLN0_NamPlt_vendor (&iedModel_LD0_LLN0_NamPlt_vendor)
#define IEDMODEL_LD0_LLN0_NamPlt_swRev (&iedModel_LD0_LLN0_NamPlt_swRev)
#define IEDMODEL_LD0_LLN0_NamPlt_d (&iedModel_LD0_LLN0_NamPlt_d)
#define IEDMODEL_LD0_LLN0_NamPlt_configRev (&iedModel_LD0_LLN0_NamPlt_configRev)
#define IEDMODEL_LD0_LLN0_NamPlt_ldNs (&iedModel_LD0_LLN0_NamPlt_ldNs)
#define IEDMODEL_LD0_LPHD1 (&iedModel_LD0_LPHD1)
#define IEDMODEL_LD0_LPHD1_PhyNam (&iedModel_LD0_LPHD1_PhyNam)
#define IEDMODEL_LD0_LPHD1_PhyNam_vendor (&iedModel_LD0_LPHD1_PhyNam_vendor)
#define IEDMODEL_LD0_LPHD1_PhyHealth (&iedModel_LD0_LPHD1_PhyHealth)
#define IEDMODEL_LD0_LPHD1_PhyHealth_stVal (&iedModel_LD0_LPHD1_PhyHealth_stVal)
#define IEDMODEL_LD0_LPHD1_PhyHealth_q (&iedModel_LD0_LPHD1_PhyHealth_q)
#define IEDMODEL_LD0_LPHD1_PhyHealth_t (&iedModel_LD0_LPHD1_PhyHealth_t)
#define IEDMODEL_LD0_LPHD1_Proxy (&iedModel_LD0_LPHD1_Proxy)
#define IEDMODEL_LD0_LPHD1_Proxy_stVal (&iedModel_LD0_LPHD1_Proxy_stVal)
#define IEDMODEL_LD0_LPHD1_Proxy_q (&iedModel_LD0_LPHD1_Proxy_q)
#define IEDMODEL_LD0_LPHD1_Proxy_t (&iedModel_LD0_LPHD1_Proxy_t)
#define IEDMODEL_LD0_GGIO1 (&iedModel_LD0_GGIO1)
#define IEDMODEL_LD0_GGIO1_Mod (&iedModel_LD0_GGIO1_Mod)
#define IEDMODEL_LD0_GGIO1_Mod_q (&iedModel_LD0_GGIO1_Mod_q)
#define IEDMODEL_LD0_GGIO1_Mod_t (&iedModel_LD0_GGIO1_Mod_t)
#define IEDMODEL_LD0_GGIO1_Mod_ctlModel (&iedModel_LD0_GGIO1_Mod_ctlModel)
#define IEDMODEL_LD0_GGIO1_Beh (&iedModel_LD0_GGIO1_Beh)
#define IEDMODEL_LD0_GGIO1_Beh_stVal (&iedModel_LD0_GGIO1_Beh_stVal)
#define IEDMODEL_LD0_GGIO1_Beh_q (&iedModel_LD0_GGIO1_Beh_q)
#define IEDMODEL_LD0_GGIO1_Beh_t (&iedModel_LD0_GGIO1_Beh_t)
#define IEDMODEL_LD0_GGIO1_Health (&iedModel_LD0_GGIO1_Health)
#define IEDMODEL_LD0_GGIO1_Health_stVal (&iedModel_LD0_GGIO1_Health_stVal)
#define IEDMODEL_LD0_GGIO1_Health_q (&iedModel_LD0_GGIO1_Health_q)
#define IEDMODEL_LD0_GGIO1_Health_t (&iedModel_LD0_GGIO1_Health_t)
#define IEDMODEL_LD0_GGIO1_NamPlt (&iedModel_LD0_GGIO1_NamPlt)
#define IEDMODEL_LD0_GGIO1_NamPlt_vendor (&iedModel_LD0_GGIO1_NamPlt_vendor)
#define IEDMODEL_LD0_GGIO1_NamPlt_swRev (&iedModel_LD0_GGIO1_NamPlt_swRev)
#define IEDMODEL_LD0_GGIO1_NamPlt_d (&iedModel_LD0_GGIO1_NamPlt_d)
#define IEDMODEL_LD0_GGIO1_Ind1 (&iedModel_LD0_GGIO1_Ind1)
#define IEDMODEL_LD0_GGIO1_Ind1_stVal (&iedModel_LD0_GGIO1_Ind1_stVal)
#define IEDMODEL_LD0_GGIO1_Ind1_q (&iedModel_LD0_GGIO1_Ind1_q)
#define IEDMODEL_LD0_GGIO1_Ind1_t (&iedModel_LD0_GGIO1_Ind1_t)
#define IEDMODEL_LD0_GGIO1_Ind2 (&iedModel_LD0_GGIO1_Ind2)
#define IEDMODEL_LD0_GGIO1_Ind2_stVal (&iedModel_LD0_GGIO1_Ind2_stVal)
#define IEDMODEL_LD0_GGIO1_Ind2_q (&iedModel_LD0_GGIO1_Ind2_q)
#define IEDMODEL_LD0_GGIO1_Ind2_t (&iedModel_LD0_GGIO1_Ind2_t)
#define IEDMODEL_LD0_GGIO1_Ind3 (&iedModel_LD0_GGIO1_Ind3)
#define IEDMODEL_LD0_GGIO1_Ind3_stVal (&iedModel_LD0_GGIO1_Ind3_stVal)
#define IEDMODEL_LD0_GGIO1_Ind3_q (&iedModel_LD0_GGIO1_Ind3_q)
#define IEDMODEL_LD0_GGIO1_Ind3_t (&iedModel_LD0_GGIO1_Ind3_t)
#define IEDMODEL_LD0_GGIO1_Ind4 (&iedModel_LD0_GGIO1_Ind4)
#define IEDMODEL_LD0_GGIO1_Ind4_stVal (&iedModel_LD0_GGIO1_Ind4_stVal)
#define IEDMODEL_LD0_GGIO1_Ind4_q (&iedModel_LD0_GGIO1_Ind4_q)
#define IEDMODEL_LD0_GGIO1_Ind4_t (&iedModel_LD0_GGIO1_Ind4_t)
#define IEDMODEL_LD0_GGIO1_Ind5 (&iedModel_LD0_GGIO1_Ind5)
#define IEDMODEL_LD0_GGIO1_Ind5_stVal (&iedModel_LD0_GGIO1_Ind5_stVal)
#define IEDMODEL_LD0_GGIO1_Ind5_q (&iedModel_LD0_GGIO1_Ind5_q)
#define IEDMODEL_LD0_GGIO1_Ind5_t (&iedModel_LD0_GGIO1_Ind5_t)
#define IEDMODEL_LD0_GGIO1_Ind6 (&iedModel_LD0_GGIO1_Ind6)
#define IEDMODEL_LD0_GGIO1_Ind6_stVal (&iedModel_LD0_GGIO1_Ind6_stVal)
#define IEDMODEL_LD0_GGIO1_Ind6_q (&iedModel_LD0_GGIO1_Ind6_q)
#define IEDMODEL_LD0_GGIO1_Ind6_t (&iedModel_LD0_GGIO1_Ind6_t)
#define IEDMODEL_LD0_GGIO1_Ind7 (&iedModel_LD0_GGIO1_Ind7)
#define IEDMODEL_LD0_GGIO1_Ind7_stVal (&iedModel_LD0_GGIO1_Ind7_stVal)
#define IEDMODEL_LD0_GGIO1_Ind7_q (&iedModel_LD0_GGIO1_Ind7_q)
#define IEDMODEL_LD0_GGIO1_Ind7_t (&iedModel_LD0_GGIO1_Ind7_t)
#define IEDMODEL_LD0_GGIO1_Ind8 (&iedModel_LD0_GGIO1_Ind8)
#define IEDMODEL_LD0_GGIO1_Ind8_stVal (&iedModel_LD0_GGIO1_Ind8_stVal)
#define IEDMODEL_LD0_GGIO1_Ind8_q (&iedModel_LD0_GGIO1_Ind8_q)
#define IEDMODEL_LD0_GGIO1_Ind8_t (&iedModel_LD0_GGIO1_Ind8_t)
#define IEDMODEL_MEAS (&iedModel_MEAS)
#define IEDMODEL_MEAS_LLN0 (&iedModel_MEAS_LLN0)
#define IEDMODEL_MEAS_LLN0_Mod (&iedModel_MEAS_LLN0_Mod)
#define IEDMODEL_MEAS_LLN0_Mod_q (&iedModel_MEAS_LLN0_Mod_q)
#define IEDMODEL_MEAS_LLN0_Mod_t (&iedModel_MEAS_LLN0_Mod_t)
#define IEDMODEL_MEAS_LLN0_Mod_ctlModel (&iedModel_MEAS_LLN0_Mod_ctlModel)
#define IEDMODEL_MEAS_LLN0_Beh (&iedModel_MEAS_LLN0_Beh)
#define IEDMODEL_MEAS_LLN0_Beh_stVal (&iedModel_MEAS_LLN0_Beh_stVal)
#define IEDMODEL_MEAS_LLN0_Beh_q (&iedModel_MEAS_LLN0_Beh_q)
#define IEDMODEL_MEAS_LLN0_Beh_t (&iedModel_MEAS_LLN0_Beh_t)
#define IEDMODEL_MEAS_LLN0_Health (&iedModel_MEAS_LLN0_Health)
#define IEDMODEL_MEAS_LLN0_Health_stVal (&iedModel_MEAS_LLN0_Health_stVal)
#define IEDMODEL_MEAS_LLN0_Health_q (&iedModel_MEAS_LLN0_Health_q)
#define IEDMODEL_MEAS_LLN0_Health_t (&iedModel_MEAS_LLN0_Health_t)
#define IEDMODEL_MEAS_LLN0_NamPlt (&iedModel_MEAS_LLN0_NamPlt)
#define IEDMODEL_MEAS_LLN0_NamPlt_vendor (&iedModel_MEAS_LLN0_NamPlt_vendor)
#define IEDMODEL_MEAS_LLN0_NamPlt_swRev (&iedModel_MEAS_LLN0_NamPlt_swRev)
#define IEDMODEL_MEAS_LLN0_NamPlt_d (&iedModel_MEAS_LLN0_NamPlt_d)
#define IEDMODEL_MEAS_LLN0_NamPlt_configRev (&iedModel_MEAS_LLN0_NamPlt_configRev)
#define IEDMODEL_MEAS_LLN0_NamPlt_ldNs (&iedModel_MEAS_LLN0_NamPlt_ldNs)
#define IEDMODEL_MEAS_LPHD1 (&iedModel_MEAS_LPHD1)
#define IEDMODEL_MEAS_LPHD1_PhyNam (&iedModel_MEAS_LPHD1_PhyNam)
#define IEDMODEL_MEAS_LPHD1_PhyNam_vendor (&iedModel_MEAS_LPHD1_PhyNam_vendor)
#define IEDMODEL_MEAS_LPHD1_PhyHealth (&iedModel_MEAS_LPHD1_PhyHealth)
#define IEDMODEL_MEAS_LPHD1_PhyHealth_stVal (&iedModel_MEAS_LPHD1_PhyHealth_stVal)
#define IEDMODEL_MEAS_LPHD1_PhyHealth_q (&iedModel_MEAS_LPHD1_PhyHealth_q)
#define IEDMODEL_MEAS_LPHD1_PhyHealth_t (&iedModel_MEAS_LPHD1_PhyHealth_t)
#define IEDMODEL_MEAS_LPHD1_Proxy (&iedModel_MEAS_LPHD1_Proxy)
#define IEDMODEL_MEAS_LPHD1_Proxy_stVal (&iedModel_MEAS_LPHD1_Proxy_stVal)
#define IEDMODEL_MEAS_LPHD1_Proxy_q (&iedModel_MEAS_LPHD1_Proxy_q)
#define IEDMODEL_MEAS_LPHD1_Proxy_t (&iedModel_MEAS_LPHD1_Proxy_t)
#define IEDMODEL_MEAS_MMXU1 (&iedModel_MEAS_MMXU1)
#define IEDMODEL_MEAS_MMXU1_Mod (&iedModel_MEAS_MMXU1_Mod)
#define IEDMODEL_MEAS_MMXU1_Mod_q (&iedModel_MEAS_MMXU1_Mod_q)
#define IEDMODEL_MEAS_MMXU1_Mod_t (&iedModel_MEAS_MMXU1_Mod_t)
#define IEDMODEL_MEAS_MMXU1_Mod_ctlModel (&iedModel_MEAS_MMXU1_Mod_ctlModel)
#define IEDMODEL_MEAS_MMXU1_Beh (&iedModel_MEAS_MMXU1_Beh)
#define IEDMODEL_MEAS_MMXU1_Beh_stVal (&iedModel_MEAS_MMXU1_Beh_stVal)
#define IEDMODEL_MEAS_MMXU1_Beh_q (&iedModel_MEAS_MMXU1_Beh_q)
#define IEDMODEL_MEAS_MMXU1_Beh_t (&iedModel_MEAS_MMXU1_Beh_t)
#define IEDMODEL_MEAS_MMXU1_Health (&iedModel_MEAS_MMXU1_Health)
#define IEDMODEL_MEAS_MMXU1_Health_stVal (&iedModel_MEAS_MMXU1_Health_stVal)
#define IEDMODEL_MEAS_MMXU1_Health_q (&iedModel_MEAS_MMXU1_Health_q)
#define IEDMODEL_MEAS_MMXU1_Health_t (&iedModel_MEAS_MMXU1_Health_t)
#define IEDMODEL_MEAS_MMXU1_NamPlt (&iedModel_MEAS_MMXU1_NamPlt)
#define IEDMODEL_MEAS_MMXU1_NamPlt_vendor (&iedModel_MEAS_MMXU1_NamPlt_vendor)
#define IEDMODEL_MEAS_MMXU1_NamPlt_swRev (&iedModel_MEAS_MMXU1_NamPlt_swRev)
#define IEDMODEL_MEAS_MMXU1_NamPlt_d (&iedModel_MEAS_MMXU1_NamPlt_d)
#define IEDMODEL_MEAS_MMXU1_Hz (&iedModel_MEAS_MMXU1_Hz)
#define IEDMODEL_MEAS_MMXU1_Hz_mag (&iedModel_MEAS_MMXU1_Hz_mag)
#define IEDMODEL_MEAS_MMXU1_Hz_mag_f (&iedModel_MEAS_MMXU1_Hz_mag_f)
#define IEDMODEL_MEAS_MMXU1_Hz_q (&iedModel_MEAS_MMXU1_Hz_q)
#define IEDMODEL_MEAS_MMXU1_Hz_t (&iedModel_MEAS_MMXU1_Hz_t)
#define IEDMODEL_MEAS_MMXU1_PhV (&iedModel_MEAS_MMXU1_PhV)
#define IEDMODEL_MEAS_MMXU1_PhV_phsA (&iedModel_MEAS_MMXU1_PhV_phsA)
#define IEDMODEL_MEAS_MMXU1_PhV_phsA_cVal (&iedModel_MEAS_MMXU1_PhV_phsA_cVal)
#define IEDMODEL_MEAS_MMXU1_PhV_phsA_cVal_mag (&iedModel_MEAS_MMXU1_PhV_phsA_cVal_mag)
#define IEDMODEL_MEAS_MMXU1_PhV_phsA_cVal_mag_f (&iedModel_MEAS_MMXU1_PhV_phsA_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU1_PhV_phsA_q (&iedModel_MEAS_MMXU1_PhV_phsA_q)
#define IEDMODEL_MEAS_MMXU1_PhV_phsA_t (&iedModel_MEAS_MMXU1_PhV_phsA_t)
#define IEDMODEL_MEAS_MMXU1_PhV_phsB (&iedModel_MEAS_MMXU1_PhV_phsB)
#define IEDMODEL_MEAS_MMXU1_PhV_phsB_cVal (&iedModel_MEAS_MMXU1_PhV_phsB_cVal)
#define IEDMODEL_MEAS_MMXU1_PhV_phsB_cVal_mag (&iedModel_MEAS_MMXU1_PhV_phsB_cVal_mag)
#define IEDMODEL_MEAS_MMXU1_PhV_phsB_cVal_mag_f (&iedModel_MEAS_MMXU1_PhV_phsB_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU1_PhV_phsB_q (&iedModel_MEAS_MMXU1_PhV_phsB_q)
#define IEDMODEL_MEAS_MMXU1_PhV_phsB_t (&iedModel_MEAS_MMXU1_PhV_phsB_t)
#define IEDMODEL_MEAS_MMXU1_PhV_phsC (&iedModel_MEAS_MMXU1_PhV_phsC)
#define IEDMODEL_MEAS_MMXU1_PhV_phsC_cVal (&iedModel_MEAS_MMXU1_PhV_phsC_cVal)
#define IEDMODEL_MEAS_MMXU1_PhV_phsC_cVal_mag (&iedModel_MEAS_MMXU1_PhV_phsC_cVal_mag)
#define IEDMODEL_MEAS_MMXU1_PhV_phsC_cVal_mag_f (&iedModel_MEAS_MMXU1_PhV_phsC_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU1_PhV_phsC_q (&iedModel_MEAS_MMXU1_PhV_phsC_q)
#define IEDMODEL_MEAS_MMXU1_PhV_phsC_t (&iedModel_MEAS_MMXU1_PhV_phsC_t)
#define IEDMODEL_MEAS_MMXU1_A (&iedModel_MEAS_MMXU1_A)
#define IEDMODEL_MEAS_MMXU1_A_phsA (&iedModel_MEAS_MMXU1_A_phsA)
#define IEDMODEL_MEAS_MMXU1_A_phsA_cVal (&iedModel_MEAS_MMXU1_A_phsA_cVal)
#define IEDMODEL_MEAS_MMXU1_A_phsA_cVal_mag (&iedModel_MEAS_MMXU1_A_phsA_cVal_mag)
#define IEDMODEL_MEAS_MMXU1_A_phsA_cVal_mag_f (&iedModel_MEAS_MMXU1_A_phsA_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU1_A_phsA_q (&iedModel_MEAS_MMXU1_A_phsA_q)
#define IEDMODEL_MEAS_MMXU1_A_phsA_t (&iedModel_MEAS_MMXU1_A_phsA_t)
#define IEDMODEL_MEAS_MMXU1_A_phsB (&iedModel_MEAS_MMXU1_A_phsB)
#define IEDMODEL_MEAS_MMXU1_A_phsB_cVal (&iedModel_MEAS_MMXU1_A_phsB_cVal)
#define IEDMODEL_MEAS_MMXU1_A_phsB_cVal_mag (&iedModel_MEAS_MMXU1_A_phsB_cVal_mag)
#define IEDMODEL_MEAS_MMXU1_A_phsB_cVal_mag_f (&iedModel_MEAS_MMXU1_A_phsB_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU1_A_phsB_q (&iedModel_MEAS_MMXU1_A_phsB_q)
#define IEDMODEL_MEAS_MMXU1_A_phsB_t (&iedModel_MEAS_MMXU1_A_phsB_t)
#define IEDMODEL_MEAS_MMXU1_A_phsC (&iedModel_MEAS_MMXU1_A_phsC)
#define IEDMODEL_MEAS_MMXU1_A_phsC_cVal (&iedModel_MEAS_MMXU1_A_phsC_cVal)
#define IEDMODEL_MEAS_MMXU1_A_phsC_cVal_mag (&iedModel_MEAS_MMXU1_A_phsC_cVal_mag)
#define IEDMODEL_MEAS_MMXU1_A_phsC_cVal_mag_f (&iedModel_MEAS_MMXU1_A_phsC_cVal_mag_f)
#define IEDMODEL_MEAS_MMXU1_A_phsC_q (&iedModel_MEAS_MMXU1_A_phsC_q)
#define IEDMODEL_MEAS_MMXU1_A_phsC_t (&iedModel_MEAS_MMXU1_A_phsC_t)

#endif /* STATIC_MODEL_H_ */

